# Generated by Django 5.0.4 on 2024-04-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="invitation",
            table="teams_invitations",
        ),
        migrations.AlterModelTable(
            name="member",
            table="teams_members",
        ),
        migrations.AlterModelTable(
            name="team",
            table="teams_teams",
        ),
    ]
