# Generated by Django 5.0.4 on 2024-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_invitation_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_default_team",
            field=models.BooleanField(default=False),
        ),
    ]
