# Generated by Django 5.1 on 2024-08-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_member_is_default_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="key",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
