# Generated by Django 5.1 on 2024-08-30 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_set_unique_team_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["key"], name="teams_teams_key_87f11a_idx"),
        ),
    ]
