# Generated by Django 5.1.4 on 2025-05-13 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0011_team_billing_plan_team_billing_plan_limits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="team",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            (
                                "billing_plan_limits__stripe_subscription_id__isnull",
                                False,
                            ),
                            ("billing_plan_limits__stripe_customer_id__isnull", False),
                        ),
                        models.Q(
                            (
                                "billing_plan_limits__stripe_subscription_id__isnull",
                                True,
                            ),
                            ("billing_plan_limits__stripe_customer_id__isnull", True),
                        ),
                        _connector="OR",
                    )
                ),
                name="valid_billing_relationship",
            ),
        ),
    ]
