# Generated by Django 5.1.4 on 2025-05-13 11:24

from django.db import migrations
from core.utils import number_to_random_token


def update_team_keys(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    for team in Team.objects.all():
        if len(team.key) < 9:
            team.key = number_to_random_token(abs(team.pk))
            team.save()


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0013_alter_team_key"),
    ]

    operations = [
        migrations.RunPython(update_team_keys, migrations.RunPython.noop),
    ]
