# Generated by Django 5.2.3 on 2025-07-03 09:46

import sbomify.apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sboms", "0031_component_component_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(default="", max_length=255)),
                ("document_filename", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(max_length=255, null=True)),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of document (e.g., specification, manual, report)",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sboms.component",
                    ),
                ),
            ],
            options={
                "db_table": "documents_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
