# Generated by Django 5.2.7 on 2026-01-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_migrate_existing_document_types_data"),
        ("sboms", "0040_component_sboms_compo_is_publ_ccec78_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="documents_d_created_bd50af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="documents_d_documen_e31b88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["component", "created_at"],
                name="documents_d_compone_fbaa0f_idx",
            ),
        ),
    ]
