# Generated by Django 5.2.7 on 2026-02-16 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_create_access_models"),
        ("teams", "0028_team_onboarding_goal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accessrequest",
            name="documents_access_requests_team_user_unique",
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved or rejected the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_access_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about the request",
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who revoked the access",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_access_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ndasignature",
            name="access_request",
            field=models.OneToOneField(
                help_text="Associated access request",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nda_signature",
                to="documents.accessrequest",
            ),
        ),
        migrations.AlterField(
            model_name="ndasignature",
            name="nda_document",
            field=models.ForeignKey(
                help_text="NDA document that was signed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nda_signatures",
                to="documents.document",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accessrequest",
            unique_together={("team", "user")},
        ),
    ]
