# Generated by Django 5.2.7 on 2026-01-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_remove_accessrequest_documents_access_requests_team_user_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="sha256_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of the document file content",
                max_length=64,
                null=True,
            ),
        ),
    ]
