# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_add_document_sha256_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="signature_url",
            field=models.URLField(
                blank=True,
                help_text="URL to a detached cryptographic signature for this document",
                max_length=500,
                null=True,
            ),
        ),
    ]
