# Generated by Django 5.2.11 on 2026-02-27 13:24

import uuid

from django.db import migrations, models


def populate_document_uuids(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    batch_size = 2000
    objs = list(Document.objects.filter(uuid__isnull=True))
    for obj in objs:
        obj.uuid = uuid.uuid4()
    for i in range(0, len(objs), batch_size):
        Document.objects.bulk_update(objs[i : i + batch_size], ["uuid"], batch_size=batch_size)


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_document_signature_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_document_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
