# Generated by Django 5.2.11 on 2026-02-27 13:24

import uuid

from django.db import migrations, models


def populate_document_uuids(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    batch_size = 2000
    batch = []
    for obj in Document.objects.filter(uuid__isnull=True).iterator(chunk_size=batch_size):
        obj.uuid = uuid.uuid4()
        batch.append(obj)
        if len(batch) >= batch_size:
            Document.objects.bulk_update(batch, ["uuid"], batch_size=batch_size)
            batch = []
    if batch:
        Document.objects.bulk_update(batch, ["uuid"], batch_size=batch_size)


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_document_signature_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_document_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
