# Generated by Django 5.2.15 on 2026-08-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_document_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndasignature",
            name="superseded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when this signature stopped satisfying the access flow — the request was rejected or access revoked — so a later re-request must sign again. NULL = live. The row itself is history and is never deleted while its request exists.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ndasignature",
            name="access_request",
            field=models.ForeignKey(
                help_text="Associated access request",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nda_signatures",
                to="documents.accessrequest",
            ),
        ),
    ]
