# Generated by Django 5.2.15 on 2026-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_ndasignature_superseded_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ndasignature",
            constraint=models.UniqueConstraint(
                condition=models.Q(("superseded_at__isnull", True)),
                fields=("access_request", "nda_document"),
                name="one_live_signature_per_request_document",
            ),
        ),
    ]
