# Generated by Django 5.2.17 on 2026-08-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_ndasignature_one_live_signature_per_request_document"),
        (
            "teams",
            "0042_rename_teams_invit_email_d19291_idx_workspaces__email_77ed9e_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accessrequest",
            new_name="documents_a_workspa_17946d_idx",
            old_name="documents_a_team_id_838fe2_idx",
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_requests",
                to="teams.team",
            ),
        ),
    ]
