# Generated by Django 5.2.3 on 2025-07-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_add_trial_periods"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingplan",
            name="max_users",
            field=models.IntegerField(
                help_text="Maximum number of users/members allowed in a team. Null means unlimited.",
                null=True,
            ),
        ),
    ]
