# Generated by Django 5.1.4 on 2025-05-15 09:08

from django.db import migrations

def backfill_user_names(apps, schema_editor):
    User = apps.get_model('core', 'User')
    SocialAccount = apps.get_model('socialaccount', 'SocialAccount')

    for user in User.objects.all():
        if not user.first_name or not user.last_name:
            sa = SocialAccount.objects.filter(user_id=user.id).first()
            if sa and hasattr(sa, 'extra_data'):
                data = sa.extra_data
                first_name = data.get('given_name') or data.get('first_name')
                last_name = data.get('family_name') or data.get('last_name')
                updated = False
                if first_name and not user.first_name:
                    user.first_name = first_name
                    updated = True
                if last_name and not user.last_name:
                    user.last_name = last_name
                    updated = True
                if updated:
                    user.save(update_fields=['first_name', 'last_name'])

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_associate_keycloak_to_site"),
    ]

    operations = [
        migrations.RunPython(backfill_user_names, reverse_code=migrations.RunPython.noop),
    ]
