# Generated by Django 5.2.17 on 2026-09-15 07:42

import django.db.models.deletion
import django.utils.timezone
import sbomify.apps.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0043_team_publish_vulnerability_posture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("vanta", "Vanta")], max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("revoked", "Needs reconnecting"),
                        ],
                        default="connected",
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField(blank=True, default="")),
                ("refresh_token", models.TextField(blank=True, default="")),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                (
                    "connected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        choices=[
                            ("never", "Not synced yet"),
                            ("running", "Syncing"),
                            ("ok", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True, default="")),
                ("last_sync_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "integrations_integration",
                "ordering": ["provider"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "provider"), name="unique_workspace_provider"
                    )
                ],
            },
        ),
    ]
