# Generated by Django 5.0.4 on 2024-05-23 14:26

import sbomify.apps.teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_invitation_table_alter_member_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(default=sbomify.apps.teams.models.calculate_invitation_expiry),
        ),
    ]
