# Generated by Django 5.1 on 2024-08-30 02:20

from django.db import migrations

from sbomify.apps.core.utils import number_to_random_token


def set_team_keys(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    for team in Team.objects.all():
        if team.pk < 0:
            team.key = str(team.pk)
        else:
            team.key = number_to_random_token(team.pk)
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_team_key"),
    ]

    operations = [
        migrations.RunPython(set_team_keys, migrations.RunPython.noop),
    ]
