# Generated by Django 5.1 on 2024-09-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_teams_teams_key_87f11a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='branding_info',
            field=models.JSONField(default=dict),
        ),
    ]
