# Generated by Django 5.1.4 on 2024-12-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0009_alter_team_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="has_completed_wizard",
            field=models.BooleanField(default=False),
        ),
    ]
