# Generated by Django 5.1.4 on 2025-01-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0010_team_has_completed_wizard"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="billing_plan",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="billing_plan_limits",
            field=models.JSONField(null=True),
        ),
    ]
