# Generated by Django 5.1.4 on 2025-05-13 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0012_team_valid_billing_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="key",
            field=models.CharField(
                max_length=30,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(9)],
            ),
        ),
    ]
