# Generated by hand to introduce workspace contact profiles.

import django.db.models.deletion
import sbomify.apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0014_update_team_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactProfile",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("supplier_name", models.CharField(blank=True, max_length=255)),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("website_urls", models.JSONField(blank=True, default=list)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_profiles",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "teams_contact_profiles",
                "ordering": ["name"],
                "unique_together": {("team", "name")},
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team",),
                        condition=models.Q(is_default=True),
                        name="unique_default_contact_profile_per_team",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactProfileContact",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="teams.contactprofile",
                    ),
                ),
            ],
            options={
                "db_table": "teams_contact_profile_contacts",
                "ordering": ["order", "name"],
                "unique_together": {("profile", "name", "email")},
            },
        ),
    ]
