# Generated by Django 5.2.7 on 2025-02-23 00:00

from django.db import migrations, models
from django.db.models import Q


def set_initial_visibility(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    community_filter = Q(billing_plan__iexact="community") | Q(billing_plan__isnull=True) | Q(billing_plan__exact="")
    # Community/unset -> public
    Team.objects.filter(community_filter).update(is_public=True)
    # Paid/custom -> private
    Team.objects.exclude(community_filter).update(is_public=False)


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0015_contact_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_public",
            field=models.BooleanField(
                default=True, help_text="Controls whether the workspace trust center is publicly accessible."
            ),
        ),
        migrations.RunPython(set_initial_visibility, reverse_code=migrations.RunPython.noop),
    ]
