# Generated by Django 5.2.7 on 2025-12-04 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0015_contact_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="custom_domain",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="team",
            name="custom_domain_last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="custom_domain_validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="custom_domain_verification_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["custom_domain"], name="teams_teams_custom__db3a3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["custom_domain_validated", "custom_domain_last_checked_at"],
                name="teams_teams_custom__c3d2ef_idx",
            ),
        ),
    ]
