# Generated by Django 5.2.7 on 2025-12-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0015_contact_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="custom_domain",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="team",
            name="custom_domain_validated",
            field=models.BooleanField(default=False),
        ),
    ]
