# Generated by Django 5.2.7 on 2025-11-15 19:54

import django.db.models.deletion
import sbomify.apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0015_contact_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDomain",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        help_text="Fully qualified domain name (e.g., trust.example.com)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the domain has been verified via DNS",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the domain is active and should be used",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the domain was successfully verified",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.OneToOneField(
                        help_text="Workspace that owns this custom domain",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_domain",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "teams_custom_domains",
                "indexes": [
                    models.Index(
                        fields=["team"], name="teams_custo_team_id_446345_idx"
                    ),
                    models.Index(
                        fields=["hostname"], name="teams_custo_hostnam_1abe08_idx"
                    ),
                    models.Index(
                        fields=["is_verified", "is_active"],
                        name="teams_custo_is_veri_77d233_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team",), name="unique_custom_domain_per_team"
                    )
                ],
            },
        ),
    ]
