# Generated by Django 5.2.7 on 2025-12-04 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0016_team_custom_domain_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["custom_domain"], name="teams_teams_custom__db3a3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["custom_domain_validated", "custom_domain_last_checked_at"],
                name="teams_teams_custom__c3d2ef_idx",
            ),
        ),
    ]
