# Generated by Django 5.2.7 on 2026-01-05 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0018_invitation_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="billing_plan",
            field=models.CharField(
                choices=[
                    ("community", "Community"),
                    ("business", "Business"),
                    ("enterprise", "Enterprise"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Controls whether the workspace Trust Center is publicly accessible.",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["email"], name="teams_invit_email_d19291_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["expires_at"], name="teams_invit_expires_5e3602_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["created_at"], name="teams_teams_created_6eb5e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["billing_plan"], name="teams_teams_billing_974e45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["is_public"], name="teams_teams_is_publ_ce6c3d_idx"
            ),
        ),
    ]
