# Generated by Django 5.2.7 on 2025-12-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0018_invitation_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="has_selected_plan",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="billing_plan",
            field=models.CharField(
                choices=[
                    ("community", "Community"),
                    ("business", "Business"),
                    ("enterprise", "Enterprise"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Controls whether the workspace Trust Center is publicly accessible.",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["email"], name="teams_invit_email_d19291_idx"),
        ),
    ]
