# Generated by Django 5.2.7 on 2026-01-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0023_member_team_role_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactprofilecontact",
            name="is_author",
            field=models.BooleanField(
                default=False,
                help_text="Person who authored the SBOM (appears in metadata.authors)",
            ),
        ),
        migrations.AddField(
            model_name="contactprofilecontact",
            name="is_security_contact",
            field=models.BooleanField(
                default=False,
                help_text="Security/vulnerability reporting contact (CRA requirement). Only one per profile.",
            ),
        ),
        migrations.AddField(
            model_name="contactprofilecontact",
            name="is_technical_contact",
            field=models.BooleanField(
                default=False, help_text="Technical point of contact"
            ),
        ),
    ]
