# Generated by Django 5.2.7 on 2026-01-19
"""
Step 1: Add new role fields to ContactProfileContact and ContactEntity.
Also add is_component_private to ContactProfile.

This must run BEFORE the data migration so the fields exist.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0023_member_team_role_index"),
    ]

    operations = [
        # Add role fields to ContactProfileContact
        migrations.AddField(
            model_name="contactprofilecontact",
            name="is_author",
            field=models.BooleanField(
                default=False,
                help_text="Person who authored the SBOM (appears in metadata.authors)",
            ),
        ),
        migrations.AddField(
            model_name="contactprofilecontact",
            name="is_security_contact",
            field=models.BooleanField(
                default=False,
                help_text="Security/vulnerability reporting contact (CRA requirement). Only one per profile.",
            ),
        ),
        migrations.AddField(
            model_name="contactprofilecontact",
            name="is_technical_contact",
            field=models.BooleanField(
                default=False,
                help_text="Technical point of contact",
            ),
        ),
        # Add is_author to ContactEntity
        migrations.AddField(
            model_name="contactentity",
            name="is_author",
            field=models.BooleanField(
                default=False,
                help_text="Entity groups individual authors (no organization info required)",
            ),
        ),
        # Make name/email optional on ContactEntity (for author-only entities)
        migrations.AlterField(
            model_name="contactentity",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contactentity",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        # Add is_component_private to ContactProfile
        migrations.AddField(
            model_name="contactprofile",
            name="is_component_private",
            field=models.BooleanField(
                default=False,
                help_text="If True, this profile is owned by a specific component and not shared at workspace level",
            ),
        ),
        # Update unique constraints on ContactProfile
        migrations.AlterUniqueTogether(
            name="contactprofile",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="contactprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_component_private", False)),
                fields=("team", "name"),
                name="unique_shared_contact_profile_name_per_team",
            ),
        ),
    ]
