# Generated by Django 5.2.7 on 2026-01-19
"""
Step 2: Data migration to move AuthorContact records to ContactProfileContact.

For each AuthorContact:
1. Find the first entity in the profile (or create one if none exists)
2. Create a ContactProfileContact with is_author=True (or update existing if same name/email)

This must run AFTER 0024 (fields exist) and BEFORE 0026 (AuthorContact deletion).
"""

from django.db import migrations

import sbomify.apps.core.utils


def migrate_authors_to_entity_contacts(apps, schema_editor):
    """Migrate AuthorContact records to ContactProfileContact with is_author=True."""
    ContactProfile = apps.get_model("teams", "ContactProfile")
    ContactEntity = apps.get_model("teams", "ContactEntity")
    ContactProfileContact = apps.get_model("teams", "ContactProfileContact")
    AuthorContact = apps.get_model("teams", "AuthorContact")

    for profile in ContactProfile.objects.all():
        authors = AuthorContact.objects.filter(profile=profile)
        if not authors.exists():
            continue

        # Get or create an entity for this profile
        entity = ContactEntity.objects.filter(profile=profile).first()

        if not entity:
            # Create a default entity using the first author's info
            first_author = authors.first()
            entity = ContactEntity.objects.create(
                id=sbomify.apps.core.utils.generate_id(),
                profile=profile,
                name=profile.name or "Default Entity",
                email=first_author.email if first_author else "",
                is_manufacturer=True,
                is_supplier=True,
                is_author=True,  # Mark entity as having author role
            )

        # Migrate each author to a ContactProfileContact with is_author=True
        for author in authors:
            # Check if a contact with the same name/email already exists in this entity
            # This handles the case where someone is both a supplier contact AND an author
            existing = ContactProfileContact.objects.filter(
                entity=entity, name=author.name, email=author.email
            ).first()

            if existing:
                # Update existing contact to also be an author
                existing.is_author = True
                existing.save(update_fields=["is_author"])
            else:
                # Create new contact
                ContactProfileContact.objects.create(
                    id=sbomify.apps.core.utils.generate_id(),
                    entity=entity,
                    name=author.name,
                    email=author.email,
                    phone=author.phone or "",
                    order=author.order,
                    is_author=True,
                    is_security_contact=False,
                    is_technical_contact=False,
                )


def migrate_entity_contacts_to_authors(apps, schema_editor):
    """Reverse migration: Create AuthorContact records from ContactProfileContact with is_author=True."""
    ContactProfile = apps.get_model("teams", "ContactProfile")
    ContactProfileContact = apps.get_model("teams", "ContactProfileContact")
    AuthorContact = apps.get_model("teams", "AuthorContact")

    for profile in ContactProfile.objects.all():
        # Find all contacts with is_author=True across all entities in this profile
        author_contacts = ContactProfileContact.objects.filter(
            entity__profile=profile, is_author=True
        )

        for contact in author_contacts:
            # Check if this author already exists (idempotency)
            existing = AuthorContact.objects.filter(
                profile=profile, name=contact.name, email=contact.email
            ).first()

            if not existing:
                AuthorContact.objects.create(
                    id=sbomify.apps.core.utils.generate_id(),
                    profile=profile,
                    name=contact.name,
                    email=contact.email,
                    phone=contact.phone or "",
                    order=contact.order,
                )


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0024_add_contact_role_fields"),
    ]

    operations = [
        migrations.RunPython(
            migrate_authors_to_entity_contacts,
            migrate_entity_contacts_to_authors,
        ),
    ]
