# Generated by Django 5.2.7 on 2026-01-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0025_migrate_author_contacts_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthorContact",
        ),
    ]
