# Generated by Django 5.2.7 on 2026-01-19
"""
Step 3: Remove the AuthorContact model after data has been migrated.

This must run AFTER 0025 (data migration) so no data is lost.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0025_migrate_author_contacts_data"),
    ]

    operations = [
        # First remove the unique_together constraint and FK before deleting
        migrations.AlterUniqueTogether(
            name="authorcontact",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="authorcontact",
            name="profile",
        ),
        # Now delete the model
        migrations.DeleteModel(
            name="AuthorContact",
        ),
    ]
