# Generated by Django 5.2.7 on 2026-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0026_remove_author_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactentity",
            name="is_author",
            field=models.BooleanField(
                default=False,
                help_text="Entity groups individual authors (no organization info required)",
            ),
        ),
        migrations.AlterField(
            model_name="contactentity",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contactentity",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
