# Generated by Django 5.2.7 on 2026-01-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0026_remove_author_contact"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactprofilecontact",
            index=models.Index(fields=["is_author"], name="contact_is_author_idx"),
        ),
        migrations.AddIndex(
            model_name="contactprofilecontact",
            index=models.Index(
                fields=["is_security_contact"], name="contact_is_security_idx"
            ),
        ),
    ]
