# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0027_add_contact_role_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="onboarding_goal",
            field=models.TextField(blank=True, default=""),
        ),
    ]
