# Generated by Django for tea_enabled field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0028_team_onboarding_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="tea_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable Transparency Exchange API (TEA) for this workspace",
            ),
        ),
    ]
