# Generated by Django 5.2.11 on 2026-03-02 09:39

import django.core.validators
import sbomify.apps.teams.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0030_team_tea_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=63,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator(
                        message="Slug must contain only lowercase letters, numbers, and hyphens, and must not start or end with a hyphen.",
                        regex="^[a-z0-9]([a-z0-9-]*[a-z0-9])?$",
                    ),
                    sbomify.apps.teams.models.validate_slug_not_reserved,
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["slug"], name="teams_teams_slug_8dc326_idx"),
        ),
    ]
