# Generated by Django 5.2.11 on 2026-03-02 09:39

from django.db import migrations
from django.utils.text import slugify

RESERVED_SLUGS = frozenset(
    {"www", "api", "app", "mail", "ftp", "admin", "staging", "dev", "test", "status", "blog", "docs", "help", "support"}
)


def populate_slugs(apps, schema_editor):
    """Populate slug for all existing teams from display_name."""
    Team = apps.get_model("teams", "Team")

    # Preload all existing slugs into memory to avoid per-candidate DB queries
    existing_slugs = set(Team.objects.exclude(slug__isnull=True).values_list("slug", flat=True))

    for team in Team.objects.filter(slug__isnull=True).order_by("pk"):
        name = team.name or ""
        # Replicate display_name logic inline (can't use model methods in migrations)
        trimmed = name.strip()
        lowered = trimmed.casefold()
        for suffix in ("'s workspace", "\u2019s workspace"):
            if lowered.endswith(suffix):
                trimmed = trimmed[: -len(suffix)].rstrip()
                break
        else:
            workspace_suffix = "workspace"
            if lowered.endswith(workspace_suffix):
                trimmed = trimmed[: -len(workspace_suffix)].rstrip(" -\u2013\u2014_:")

        base = slugify(trimmed, allow_unicode=False).strip("-")
        if len(base) < 3:
            base = (base or "workspace").ljust(3, "0")
        base = base[:63].rstrip("-")

        candidate = base
        suffix_num = 2
        while candidate in RESERVED_SLUGS or candidate in existing_slugs:
            max_base_len = 63 - len(f"-{suffix_num}")
            candidate = f"{base[:max_base_len].rstrip('-')}-{suffix_num}"
            suffix_num += 1

        team.slug = candidate
        team.save(update_fields=["slug"])
        existing_slugs.add(candidate)


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0031_add_team_slug"),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
    ]
