# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0032_populate_team_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="security_txt_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="RFC 9116 security.txt configuration. Keys: enabled, expires, contact_id, policy_url, "
                "encryption_url, acknowledgments_url, hiring_url, preferred_languages, canonical_url",
            ),
        ),
    ]
