# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0033_add_security_txt_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="security_txt_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="RFC 9116 security.txt configuration. Keys: enabled (bool), expires (ISO 8601), "
                "contact_id (str), policy_url (str), encryption_urls (list[str]), encryption_url (str, legacy), "
                "acknowledgments_url (str), canonical_url (str), hiring_url (str), preferred_languages (str)",
            ),
        ),
    ]
