# Generated by Django 5.2.14 on 2026-05-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0034_alter_team_security_txt_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("guest", "Guest"),
                    ("bot", "Bot"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("guest", "Guest"),
                    ("bot", "Bot"),
                ],
                max_length=255,
            ),
        ),
    ]
