# Generated by Django 5.2.14 on 2026-05-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0035_alter_invitation_role_alter_member_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                # Excludes only ``bot`` (reserved for OIDC synthetic
                # identities). ``guest`` stays valid because the
                # trust-center auto-accept flow creates guest-role
                # Invitation rows.
                choices=[("owner", "Owner"), ("admin", "Admin"), ("guest", "Guest")],
                max_length=255,
            ),
        ),
    ]
