# Generated by Django 5.2.14 on 2026-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0036_alter_invitation_role"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("role", "bot"), _negated=True),
                name="invitation_role_not_bot",
            ),
        ),
    ]
