# Generated by Django 5.2.14 on 2026-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0037_invitation_invitation_role_not_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="sbom_freshness_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Days an SBOM stays current before its component is flagged stale. Empty means no freshness policy.",
                null=True,
            ),
        ),
    ]
