# Generated by Django 5.2.14 on 2026-07-29 12:12

import django.db.models.deletion
import django.db.models.functions.text
import sbomify.apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0037_invitation_invitation_role_not_bot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The vendor organization's name", max_length=255
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who to address at the vendor. Optional: a shared alias often has no person behind it",
                        max_length=255,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Where requests are sent. Blank until known, so a vendor can be tracked before a contact is found",
                        max_length=254,
                    ),
                ),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "teams_suppliers",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["team", "name"], name="teams_supplier_team_name_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("team"),
                        name="unique_supplier_name_per_team",
                    )
                ],
            },
        ),
    ]
