# Generated by Django 5.2.14 on 2026-07-30 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0038_supplier"),
        ("teams", "0038_team_sbom_freshness_days"),
    ]

    operations = []
