# Generated by Django 5.2.14 on 2026-08-04 07:34

import sbomify.apps.teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0039_merge_0038_supplier_0038_team_sbom_freshness_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="patch_sla_days",
            field=models.JSONField(
                blank=True,
                default=sbomify.apps.teams.models.default_patch_sla_days,
                help_text="Maximum days to remediate by severity (CRA checklist 4.1.4). A severity mapped to null is best-effort and excluded from the SLA compliance KPI.",
            ),
        ),
    ]
