# Generated by Django 5.2.17 on 2026-08-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Hard rename of the teams_* tables to workspaces_*.

    Not a rolling migration: code from before this change breaks the moment
    it applies, so it must ship inside one deploy with the code that reads
    the new names.
    """

    dependencies = [
        ("teams", "0041_member_role"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="member",
            new_name="workspace_member_role_idx",
            old_name="teams_member_team_role_idx",
        ),
        migrations.RenameIndex(
            model_name="supplier",
            new_name="workspace_supplier_name_idx",
            old_name="teams_supplier_team_name_idx",
        ),
        migrations.RenameIndex(
            model_name="invitation",
            new_name="workspaces__email_77ed9e_idx",
            old_name="teams_invit_email_d19291_idx",
        ),
        migrations.RenameIndex(
            model_name="invitation",
            new_name="workspaces__expires_ef1372_idx",
            old_name="teams_invit_expires_5e3602_idx",
        ),
        migrations.RenameIndex(
            model_name="team",
            new_name="workspaces__key_a1a6b8_idx",
            old_name="teams_teams_key_87f11a_idx",
        ),
        migrations.RenameIndex(
            model_name="team",
            new_name="workspaces__slug_3ada81_idx",
            old_name="teams_teams_slug_8dc326_idx",
        ),
        migrations.RenameIndex(
            model_name="team",
            new_name="workspaces__custom__69b441_idx",
            old_name="teams_teams_custom__db3a3f_idx",
        ),
        migrations.RenameIndex(
            model_name="team",
            new_name="workspaces__custom__20a2bd_idx",
            old_name="teams_teams_custom__c3d2ef_idx",
        ),
        migrations.RenameIndex(
            model_name="team",
            new_name="workspaces__created_5dd57c_idx",
            old_name="teams_teams_created_6eb5e5_idx",
        ),
        migrations.RenameIndex(
            model_name="team",
            new_name="workspaces__billing_a2f353_idx",
            old_name="teams_teams_billing_974e45_idx",
        ),
        migrations.RenameIndex(
            model_name="team",
            new_name="workspaces__is_publ_ae9dfe_idx",
            old_name="teams_teams_is_publ_ce6c3d_idx",
        ),
        migrations.AlterField(
            model_name="contactprofile",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_profiles",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="is_default_team",
            field=models.BooleanField(db_column="is_default_workspace", default=False),
        ),
        migrations.AlterField(
            model_name="member",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppliers",
                to="teams.team",
            ),
        ),
        migrations.AlterModelTable(
            name="contactentity",
            table="workspaces_contact_entities",
        ),
        migrations.AlterModelTable(
            name="contactprofile",
            table="workspaces_contact_profiles",
        ),
        migrations.AlterModelTable(
            name="contactprofilecontact",
            table="workspaces_contact_profile_contacts",
        ),
        migrations.AlterModelTable(
            name="invitation",
            table="workspaces_invitations",
        ),
        migrations.AlterModelTable(
            name="member",
            table="workspaces_members",
        ),
        migrations.AlterModelTable(
            name="supplier",
            table="workspaces_suppliers",
        ),
        migrations.AlterModelTable(
            name="team",
            table="workspaces_workspaces",
        ),
    ]
