# Generated by Django 5.2.17 on 2026-09-23 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0044_team_csaf_feed_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="default_support_period_years",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Default support period for new product assessments. Product support dates take precedence.",
                null=True,
                validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
