# Generated by Django 5.2.7 on 2026-01-06 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access_tokens", "0001_initial"),
        ("sboms", "0041_remove_sbom_sboms_sboms_ntia_co_39ce69_idx_and_more"),
        ("teams", "0019_alter_team_billing_plan_alter_team_is_public_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredPlugin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique plugin identifier (e.g., 'checksum', 'ntia', 'osv')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for UI display", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what the plugin does"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("license", "License"),
                            ("compliance", "Compliance"),
                            ("attestation", "Attestation"),
                        ],
                        help_text="Assessment category for classification",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Current version of the plugin", max_length=50
                    ),
                ),
                (
                    "plugin_class_path",
                    models.CharField(
                        help_text="Python import path to the plugin class (e.g., 'sbomify.apps.plugins.builtins.ChecksumPlugin')",
                        max_length=500,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the plugin is available for teams to use",
                    ),
                ),
                (
                    "default_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default configuration for the plugin",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Registered Plugin",
                "verbose_name_plural": "Registered Plugins",
                "db_table": "plugins_registered_plugins",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_enabled"], name="plugins_reg_is_enab_9e4e7e_idx"
                    ),
                    models.Index(
                        fields=["category"], name="plugins_reg_categor_b22b90_idx"
                    ),
                    models.Index(fields=["name"], name="plugins_reg_name_260e23_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssessmentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plugin_name",
                    models.CharField(
                        help_text="Plugin identifier (e.g., 'ntia-minimum-elements')",
                        max_length=100,
                    ),
                ),
                (
                    "plugin_version",
                    models.CharField(
                        help_text="Plugin version (e.g., '1.2.0')", max_length=50
                    ),
                ),
                (
                    "plugin_config_hash",
                    models.CharField(
                        help_text="SHA256 hash of plugin configuration", max_length=64
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("license", "License"),
                            ("compliance", "Compliance"),
                            ("attestation", "Attestation"),
                        ],
                        help_text="Assessment category",
                        max_length=20,
                    ),
                ),
                (
                    "run_reason",
                    models.CharField(
                        choices=[
                            ("on_upload", "On Upload"),
                            ("scheduled_refresh", "Scheduled Refresh"),
                            ("manual", "Manual"),
                            ("config_change", "Config Change"),
                            ("plugin_update", "Plugin Update"),
                        ],
                        help_text="Why this assessment was triggered",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the assessment run",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When the assessment started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the assessment completed", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if the assessment failed"
                    ),
                ),
                (
                    "input_content_digest",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 of SBOM content for auditability",
                        max_length=64,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        help_text="Assessment result following AssessmentResult schema",
                        null=True,
                    ),
                ),
                (
                    "result_schema_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version of the result schema",
                        max_length=10,
                    ),
                ),
                (
                    "raw_output_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 key for raw tool output (optional)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sbom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_runs",
                        to="sboms.sbom",
                    ),
                ),
                (
                    "triggered_by_token",
                    models.ForeignKey(
                        blank=True,
                        help_text="API token used to trigger the run (null for UI or automated runs)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_assessment_runs",
                        to="access_tokens.accesstoken",
                    ),
                ),
                (
                    "triggered_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered a manual run (null for automated runs)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_assessment_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Run",
                "verbose_name_plural": "Assessment Runs",
                "db_table": "plugins_assessment_runs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sbom", "plugin_name", "-created_at"],
                        name="plugins_ass_sbom_id_79936e_idx",
                    ),
                    models.Index(
                        fields=[
                            "sbom",
                            "plugin_name",
                            "plugin_config_hash",
                            "-created_at",
                        ],
                        name="plugins_ass_sbom_id_6cac24_idx",
                    ),
                    models.Index(
                        fields=["category", "-created_at"],
                        name="plugins_ass_categor_0d6a21_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="plugins_ass_status_f7320c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamPluginSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enabled_plugins",
                    models.JSONField(
                        default=list,
                        help_text="List of enabled plugin names (e.g., ['checksum', 'ntia', 'osv'])",
                    ),
                ),
                (
                    "plugin_configs",
                    models.JSONField(
                        default=dict,
                        help_text="Plugin-specific configuration overrides (e.g., {'license-policy': {'allowed': ['MIT']}})",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_settings",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Plugin Settings",
                "verbose_name_plural": "Team Plugin Settings",
                "db_table": "plugins_team_settings",
                "indexes": [
                    models.Index(fields=["team"], name="plugins_tea_team_id_fb6782_idx")
                ],
            },
        ),
    ]
