# Generated by Django 5.2.7 on 2026-01-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessmentrun",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Assessment Run",
                "verbose_name_plural": "Assessment Runs",
            },
        ),
        migrations.AlterModelOptions(
            name="registeredplugin",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Registered Plugin",
                "verbose_name_plural": "Registered Plugins",
            },
        ),
        migrations.AlterModelOptions(
            name="teampluginsettings",
            options={
                "verbose_name": "Team Plugin Settings",
                "verbose_name_plural": "Team Plugin Settings",
            },
        ),
    ]
