# Generated by Django 5.2.7 on 2026-01-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredplugin",
            name="is_beta",
            field=models.BooleanField(
                default=False,
                help_text="Whether the plugin is in beta status (shown with beta badge in UI)",
            ),
        ),
    ]
