# Generated by Django 5.2.7 on 2026-02-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0002_add_is_beta_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredplugin",
            name="dependencies",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Plugin dependencies specifying required assessments. Schema: {"requires_one_of": [{"type": "category|plugin", "value": "..."}], "requires_all": [{"type": "category|plugin", "value": "..."}]}',
            ),
        ),
    ]
