# Generated by Django 5.2.12 on 2026-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0007_add_is_builtin_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredplugin",
            name="requires_release",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When True, this plugin only runs for SBOMs that are linked to a release via ReleaseArtifact. "
                    "Such plugins are triggered from ReleaseArtifact post_save rather than SBOM post_save."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="assessmentrun",
            name="run_reason",
            field=models.CharField(
                choices=[
                    ("on_upload", "On Upload"),
                    ("scheduled_refresh", "Scheduled Refresh"),
                    ("manual", "Manual"),
                    ("config_change", "Config Change"),
                    ("plugin_update", "Plugin Update"),
                    ("on_release_association", "On Release Association"),
                ],
                help_text="Why this assessment was triggered",
                max_length=50,
            ),
        ),
    ]
