# Generated by Django 5.2.12 on 2026-04-08 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_tokens", "0005_remove_accesstoken_access_toke_encoded_af10d4_idx"),
        ("core", "0025_unique_sbom_per_component_release"),
        ("plugins", "0008_registeredplugin_requires_release"),
        ("sboms", "0055_simplify_component_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentrun",
            name="release",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "The Release this assessment run targeted, if the trigger was scoped to a specific "
                    "release association. Null for SBOM-level triggers (upload, manual) AND for historical "
                    "runs whose release was later deleted — the run itself is preserved as audit evidence "
                    "via SET_NULL. Release-per-pair plugins like Dependency Track use this to track scans "
                    "per (SBOM, Release)."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_runs",
                to="core.release",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentrun",
            index=models.Index(
                fields=["sbom", "release", "plugin_name", "-created_at"],
                name="plugins_ass_sbom_id_dc418a_idx",
            ),
        ),
    ]
