# Generated by Django 5.2.12 on 2026-04-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0009_assessmentrun_release"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registeredplugin",
            name="requires_release",
        ),
    ]
