# Generated by Django 5.2.12 on 2026-04-08 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_releases_m2m_from_fk(apps, schema_editor):
    """Backfill AssessmentRun.releases M2M from the deprecated ``release`` FK.

    Every pre-refactor AssessmentRun either has release=NULL (SBOM-level
    plugins like NTIA) or release=<one release>. For the latter, we insert
    a single AssessmentRunRelease row so the new M2M reflects the same
    release the legacy FK pointed at. Runs with release=NULL stay with an
    empty M2M — that's the correct representation for SBOM-level runs.

    This runs once during the schema migration. It's idempotent: if the
    row already exists it's skipped. Safe to rerun in tests.
    """
    AssessmentRun = apps.get_model("plugins", "AssessmentRun")
    AssessmentRunRelease = apps.get_model("plugins", "AssessmentRunRelease")

    qs = AssessmentRun.objects.filter(release__isnull=False).values_list("id", "release_id")
    rows = [
        AssessmentRunRelease(assessment_run_id=run_id, release_id=release_id)
        for run_id, release_id in qs.iterator(chunk_size=500)
    ]
    if rows:
        AssessmentRunRelease.objects.bulk_create(rows, ignore_conflicts=True, batch_size=500)


def reverse_backfill_releases_m2m(apps, schema_editor):
    """Reverse: clear all AssessmentRunRelease rows.

    The forward migration only added rows that mirror the legacy FK, so
    wiping them on reverse restores the pre-migration state exactly.
    """
    AssessmentRunRelease = apps.get_model("plugins", "AssessmentRunRelease")
    AssessmentRunRelease.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_unique_sbom_per_component_release"),
        ("plugins", "0010_remove_requires_release"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentrun",
            name="release",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: being removed in a follow-up migration. Use the ``releases`` M2M instead. Still populated by the orchestrator during Stage 1 of the refactor for backward compatibility with queries that haven't been migrated yet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_runs_legacy",
                to="core.release",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentRunRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_associations",
                        to="plugins.assessmentrun",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_associations",
                        to="core.release",
                    ),
                ),
            ],
            options={
                "db_table": "plugins_assessment_run_releases",
            },
        ),
        migrations.AddField(
            model_name="assessmentrun",
            name="releases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Releases whose SBOM this run's result covers. Populated from ReleaseArtifact state at scan time and updated when new associations are created. Empty for SBOM-level plugin runs (e.g. NTIA) that are deterministic on bytes regardless of release context.",
                related_name="assessment_runs",
                through="plugins.AssessmentRunRelease",
                to="core.release",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentrunrelease",
            index=models.Index(
                fields=["assessment_run", "release"],
                name="plugins_ass_assessm_49f11b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentrunrelease",
            index=models.Index(
                fields=["release", "assessment_run"],
                name="plugins_ass_release_d254c5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assessmentrunrelease",
            unique_together={("assessment_run", "release")},
        ),
        migrations.RunPython(
            backfill_releases_m2m_from_fk,
            reverse_backfill_releases_m2m,
            elidable=True,
        ),
    ]
