# Generated by Django 5.2.12 on 2026-04-09 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0011_add_assessment_run_releases_m2m"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assessmentrun",
            name="plugins_ass_sbom_id_dc418a_idx",
        ),
        migrations.RemoveField(
            model_name="assessmentrun",
            name="release",
        ),
    ]
