# Generated by Django 5.2.12 on 2026-04-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0013_remove_github_attestation_plugin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentrun",
            name="run_reason",
            field=models.CharField(
                choices=[
                    ("on_upload", "On Upload"),
                    ("scheduled_refresh", "Scheduled Refresh"),
                    ("manual", "Manual"),
                    ("config_change", "Config Change"),
                    ("plugin_update", "Plugin Update"),
                    ("on_release_association", "On Release Association"),
                    ("dependency_changed", "Dependency Changed"),
                ],
                help_text="Why this assessment was triggered",
                max_length=50,
            ),
        ),
    ]
