# Generated by Django 5.2.17 on 2026-08-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0017_vulnerabilitylifecycle"),
        (
            "teams",
            "0042_rename_teams_invit_email_d19291_idx_workspaces__email_77ed9e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teampluginsettings",
            options={
                "verbose_name": "Workspace Plugin Settings",
                "verbose_name_plural": "Workspace Plugin Settings",
            },
        ),
        migrations.RenameIndex(
            model_name="teampluginsettings",
            new_name="plugins_wor_workspa_ee7cb7_idx",
            old_name="plugins_tea_team_id_fb6782_idx",
        ),
        migrations.AlterField(
            model_name="teampluginsettings",
            name="team",
            field=models.OneToOneField(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plugin_settings",
                to="teams.team",
            ),
        ),
        migrations.AlterModelTable(
            name="teampluginsettings",
            table="plugins_workspace_settings",
        ),
    ]
