# Generated by Django 5.2.17 on 2026-10-05 14:32

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0012_store_token_hash"),
        ("core", "0030_user_email_case_insensitive_unique"),
        ("plugins", "0019_drop_cra_compliance_from_team_settings"),
        (
            "sboms",
            "0068_rename_sboms_compo_team_id_fe2066_idx_sboms_compo_workspa_3edbe9_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assessmentrun",
            index=models.Index(
                models.F("plugin_name"),
                models.OrderBy(
                    django.db.models.functions.comparison.Coalesce(
                        "completed_at", "created_at"
                    ),
                    descending=True,
                ),
                name="plugins_run_plugin_settled_idx",
            ),
        ),
    ]
