# Generated by Django 5.2.17 on 2026-09-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0019_drop_cra_compliance_from_team_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessmentrun",
            name="triggered_by_token",
        ),
    ]
