# Generated by Django 5.2.17 on 2026-09-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0020_remove_assessmentrun_triggered_by_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessmentrun",
            name="raw_output_key",
        ),
    ]
