# Generated by Django 5.2.17 on 2026-09-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0021_assessmentrun_plugins_run_sbom_settled_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessmentrun",
            name="triggered_by_token",
        ),
    ]
