# Generated by Django 5.2.17 on 2026-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0021_remove_assessmentrun_raw_output_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentrun",
            name="category",
            field=models.CharField(
                choices=[
                    ("security", "Security"),
                    ("compliance", "Compliance"),
                    ("attestation", "Attestation"),
                ],
                help_text="Assessment category",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assessmentrun",
            name="run_reason",
            field=models.CharField(
                choices=[
                    ("on_upload", "On Upload"),
                    ("scheduled_refresh", "Scheduled Refresh"),
                    ("manual", "Manual"),
                    ("config_change", "Config Change"),
                    ("on_release_association", "On Release Association"),
                    ("dependency_changed", "Dependency Changed"),
                ],
                help_text="Why this assessment was triggered",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="registeredplugin",
            name="category",
            field=models.CharField(
                choices=[
                    ("security", "Security"),
                    ("compliance", "Compliance"),
                    ("attestation", "Attestation"),
                ],
                help_text="Assessment category for classification",
                max_length=20,
            ),
        ),
    ]
