# Generated by Django 5.2.17 on 2026-10-09 17:01

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # CONCURRENTLY, so the scan workers can keep writing runs while this builds:
    # a plain CREATE INDEX blocks writes to the table for the whole build.
    # Concurrent builds cannot run inside a transaction, hence atomic = False.
    atomic = False

    dependencies = [
        ("access_tokens", "0012_store_token_hash"),
        ("core", "0030_user_email_case_insensitive_unique"),
        ("plugins", "0022_assessmentrun_result_object_key"),
        ("sboms", "0068_rename_sboms_compo_team_id_fe2066_idx_sboms_compo_workspa_3edbe9_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="assessmentrun",
            index=models.Index(
                condition=models.Q(("result__isnull", False), ("result_object_key", "")),
                fields=["created_at", "id"],
                name="plugins_ar_offload_idx",
            ),
        ),
    ]
