# Generated by Django 5.0.4 on 2024-06-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbom",
            name="source",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="license_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
