# Generated by Django 5.0.4 on 2024-06-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0002_sbom_source_alter_package_license_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="cpe_id",
            new_name="purl",
        ),
        migrations.AddField(
            model_name="package",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
