# Generated by Django 5.0.4 on 2024-06-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0005_alter_sbom_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbom",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
