# Generated by Django 5.0.4 on 2024-07-16 05:26
# Data migration for removing existing sboms and projects

from django.db import migrations


def remove_existing_project_and_sbom_records(apps, schema_editor):
    SBOMPackage = apps.get_model("sboms", "SBOMPackage")
    Package = apps.get_model("sboms", "Package")
    SBOM = apps.get_model("sboms", "SBOM")
    Project = apps.get_model("sboms", "Project")

    SBOMPackage.objects.all().delete()
    Package.objects.all().delete()
    SBOM.objects.all().delete()
    Project.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0009_auto_20240708_2340"),
    ]

    operations = [
        migrations.RunPython(remove_existing_project_and_sbom_records),
    ]
