# Generated by Django 5.0.4 on 2024-07-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0016_alter_component_is_public_alter_project_is_public"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productproject",
            table="sboms_products_projects",
        ),
    ]
