# Generated by Django 5.0.4 on 2024-07-26 06:03

from django.db import migrations, models


def remove_duplicate_components(apps, schema_editor):
    Component = apps.get_model("sboms", "Component")
    SBOM = apps.get_model("sboms", "SBOM")

    # Get count of components grouped by team and name
    component_count = Component.objects.values("team", "name").annotate(count=models.Count("id"))

    # For each component in component_count keep only one record and delete the rest
    for component in component_count:
        for ctd in Component.objects.filter(
            team=component["team"], name=component["name"]
        ).order_by("id")[1:]:
            SBOM.objects.filter(component=ctd).delete()
            ctd.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0017_alter_productproject_table"),

    ]

    operations = [
        migrations.RunPython(remove_duplicate_components),
    ]
