# Generated by Django 5.0.4 on 2024-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0018_alter_component_unique_together_sbom_version_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="license_name",
            new_name="license",
        ),
        migrations.AddField(
            model_name="sbom",
            name="license",
            field=models.CharField(default="", max_length=255),
        ),
    ]
