# Generated by Django 5.1 on 2024-09-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sboms', '0023_remove_sbom_packages_remove_sbompackage_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbom',
            name='data',
        ),
        migrations.AddField(
            model_name='sbom',
            name='sbom_filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
