# Generated by Django 5.1 on 2024-11-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0025_component_metadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="sbom",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="sbom",
            name="license",
        ),
        migrations.AddField(
            model_name="sbom",
            name="licenses",
            field=models.JSONField(default=list),
        ),
    ]
