# Generated by Django 5.1 on 2024-11-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0026_alter_component_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbom",
            name="packages_licenses",
            field=models.JSONField(default=dict),
        ),
    ]
