# Generated by Django 5.1 on 2024-11-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0027_project_metadata"),
        ("sboms", "0027_sbom_packages_licenses"),
    ]

    operations = []
