# Generated by Django 5.2.3 on 2025-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0030_remove_sbom_licenses_remove_sbom_packages_licenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="component_type",
            field=models.CharField(
                choices=[("sbom", "SBOM"), ("document", "Document")],
                default="sbom",
                help_text="Type of component (SBOM, Document, etc.)",
                max_length=20,
            ),
        ),
    ]
