# Generated by Django 5.2.3 on 2025-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0031_component_component_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbom",
            name="ntia_compliance_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the NTIA compliance check was last performed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sbom",
            name="ntia_compliance_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed NTIA compliance validation results",
            ),
        ),
        migrations.AddField(
            model_name="sbom",
            name="ntia_compliance_status",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("non_compliant", "Non-Compliant"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="NTIA minimum elements compliance status",
                max_length=20,
            ),
        ),
    ]
