# Generated by Django 5.2.3 on 2025-07-07 14:59

import sbomify.apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0032_add_ntia_compliance_fields"),
        ("teams", "0014_update_team_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductIdentifier",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("gtin_12", "GTIN-12 (UPC-A)"),
                            ("gtin_13", "GTIN-13 (EAN-13)"),
                            ("gtin_14", "GTIN-14 / ITF-14"),
                            ("gtin_8", "GTIN-8"),
                            ("sku", "SKU"),
                            ("mpn", "MPN"),
                            ("asin", "ASIN"),
                            ("gs1_gpc_brick", "GS1 GPC Brick code"),
                            ("cpe", "CPE"),
                            ("purl", "PURL"),
                        ],
                        help_text="Type of product identifier",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(help_text="The identifier value", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="sboms.product",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
            ],
            options={
                "db_table": "sboms_product_identifiers",
                "ordering": ["identifier_type", "value"],
                "unique_together": {("team", "identifier_type", "value")},
            },
        ),
    ]
