# Generated by Django 5.2.3 on 2025-07-07 16:10

import sbomify.apps.core.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0033_add_product_identifiers"),
        ("teams", "0014_update_team_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("support", "Support"),
                            ("documentation", "Documentation"),
                            ("repository", "Repository"),
                            ("changelog", "Changelog"),
                            ("release_notes", "Release Notes"),
                            ("security", "Security"),
                            ("issue_tracker", "Issue Tracker"),
                            ("download", "Download"),
                            ("chat", "Chat/Community"),
                            ("social", "Social Media"),
                            ("other", "Other"),
                        ],
                        help_text="Type of product link",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title for the link", max_length=255
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The URL",
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the link"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="sboms.product",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
            ],
            options={
                "db_table": "sboms_product_links",
                "ordering": ["link_type", "title"],
                "unique_together": {("team", "link_type", "url")},
            },
        ),
    ]
