# Generated by hand to link components with workspace contact profiles.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0015_contact_profiles"),
        ("sboms", "0036_add_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="contact_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace contact profile linked to this component",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="teams.contactprofile",
            ),
        ),
    ]
