# Generated by Django 5.2.7 on 2025-11-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0037_component_contact_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="Whether the component is available at the workspace level rather than scoped to a project",
            ),
        ),
    ]
