# Generated by Django 5.2.7 on 2026-01-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0039_alter_productlink_unique_together"),
        ("teams", "0019_alter_team_billing_plan_alter_team_is_public_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["is_public"], name="sboms_compo_is_publ_ccec78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["team", "created_at"], name="sboms_compo_team_id_fe2066_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["team", "is_public"], name="sboms_compo_team_id_76162f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["component_type"], name="sboms_compo_compone_d7b240_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_public"], name="sboms_produ_is_publ_f69fd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["team", "created_at"], name="sboms_produ_team_id_c11cd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["team", "is_public"], name="sboms_produ_team_id_071f2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_public"], name="sboms_proje_is_publ_9ec90a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["team", "created_at"], name="sboms_proje_team_id_edf680_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["team", "is_public"], name="sboms_proje_team_id_5cb5de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sbom",
            index=models.Index(
                fields=["created_at"], name="sboms_sboms_created_dd66cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sbom",
            index=models.Index(
                fields=["component", "created_at"],
                name="sboms_sboms_compone_d201a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sbom",
            index=models.Index(
                fields=["ntia_compliance_status"], name="sboms_sboms_ntia_co_39ce69_idx"
            ),
        ),
    ]
