# Generated by Django 5.2.7 on 2026-01-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0040_component_sboms_compo_is_publ_ccec78_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sbom",
            name="sboms_sboms_ntia_co_39ce69_idx",
        ),
        migrations.RemoveField(
            model_name="sbom",
            name="ntia_compliance_checked_at",
        ),
        migrations.RemoveField(
            model_name="sbom",
            name="ntia_compliance_details",
        ),
        migrations.RemoveField(
            model_name="sbom",
            name="ntia_compliance_status",
        ),
    ]
