# Generated by Django 5.2.7 on 2026-01-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0041_remove_sbom_sboms_sboms_ntia_co_39ce69_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productlink",
            unique_together=set(),
        ),
    ]
