# Generated by Django 5.2.7 on 2026-01-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0042_remove_productlink_unique_constraint"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sbom",
            constraint=models.UniqueConstraint(
                fields=("component", "version", "format"),
                name="unique_sbom_per_component_version_format",
            ),
        ),
    ]
