# Generated by Django 5.2.7 on 2026-01-14 14:42

import django.db.models.deletion
import sbomify.apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0042_remove_productlink_unique_constraint"),
        ("teams", "0023_team_tea_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentIdentifier",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("gtin_12", "GTIN-12 (UPC-A)"),
                            ("gtin_13", "GTIN-13 (EAN-13)"),
                            ("gtin_14", "GTIN-14 / ITF-14"),
                            ("gtin_8", "GTIN-8"),
                            ("sku", "SKU"),
                            ("mpn", "MPN"),
                            ("asin", "ASIN"),
                            ("gs1_gpc_brick", "GS1 GPC Brick code"),
                            ("cpe", "CPE"),
                            ("purl", "PURL"),
                        ],
                        help_text="Type of component identifier",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The identifier value (version-less)", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="sboms.component",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
            ],
            options={
                "db_table": "sboms_component_identifiers",
                "ordering": ["identifier_type", "value"],
                "unique_together": {("team", "identifier_type", "value")},
            },
        ),
    ]
