# Generated by Django 5.2.7 on 2026-01-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0046_remove_component_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbom",
            name="sha256_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of the SBOM file content",
                max_length=64,
                null=True,
            ),
        ),
    ]
