# Generated by Django 5.2.7 on 2026-02-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0046_remove_component_is_public"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="component",
            new_name="sboms_compo_visibil_03f093_idx",
            old_name="sboms_component_visibility_idx",
        ),
        migrations.RenameIndex(
            model_name="component",
            new_name="sboms_compo_team_id_b000be_idx",
            old_name="sboms_component_team_visibility_idx",
        ),
        migrations.AlterField(
            model_name="component",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="component",
            name="supplier_url",
            field=models.JSONField(
                blank=True, default=list, help_text="List of supplier URLs"
            ),
        ),
    ]
