# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sboms", "0048_add_sbom_sha256_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbom",
            name="signature_url",
            field=models.URLField(
                blank=True,
                help_text="URL to a detached cryptographic signature for this SBOM",
                max_length=500,
                null=True,
            ),
        ),
    ]
