# Generated by Django 5.2.11 on 2026-02-27 13:24

import uuid

from django.db import migrations, models


def _bulk_populate_uuids(model_class, batch_size=2000):
    batch = []
    for obj in model_class.objects.filter(uuid__isnull=True).iterator(chunk_size=batch_size):
        obj.uuid = uuid.uuid4()
        batch.append(obj)
        if len(batch) >= batch_size:
            model_class.objects.bulk_update(batch, ["uuid"], batch_size=batch_size)
            batch = []
    if batch:
        model_class.objects.bulk_update(batch, ["uuid"], batch_size=batch_size)


def populate_component_uuids(apps, schema_editor):
    _bulk_populate_uuids(apps.get_model("sboms", "Component"))


def populate_product_uuids(apps, schema_editor):
    _bulk_populate_uuids(apps.get_model("sboms", "Product"))


def populate_sbom_uuids(apps, schema_editor):
    _bulk_populate_uuids(apps.get_model("sboms", "SBOM"))


class Migration(migrations.Migration):
    dependencies = [
        ("sboms", "0049_sbom_signature_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_component_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="component",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_product_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="sbom",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_sbom_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sbom",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
