# Generated by Django 5.2.12 on 2026-03-12 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0051_add_sbom_qualifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCLEEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("released", "Released"),
                            ("endOfDevelopment", "End of Development"),
                            ("endOfSupport", "End of Support"),
                            ("endOfLife", "End of Life"),
                            ("endOfDistribution", "End of Distribution"),
                            ("endOfMarketing", "End of Marketing"),
                            ("supersededBy", "Superseded By"),
                            ("componentRenamed", "Component Renamed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=30,
                    ),
                ),
                ("effective", models.DateTimeField()),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("version", models.CharField(blank=True, default="", max_length=255)),
                ("versions", models.JSONField(blank=True, default=list)),
                (
                    "support_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("license", models.CharField(blank=True, default="", max_length=255)),
                (
                    "superseded_by_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("identifiers", models.JSONField(blank=True, default=list)),
                (
                    "withdrawn_event_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("references", models.JSONField(blank=True, default=list)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cle_events",
                        to="sboms.product",
                    ),
                ),
            ],
            options={
                "db_table": "sboms_product_cle_events",
                "ordering": ["-event_id"],
                "unique_together": {("product", "event_id")},
            },
        ),
        migrations.CreateModel(
            name="ProductCLESupportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("support_id", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cle_support_definitions",
                        to="sboms.product",
                    ),
                ),
            ],
            options={
                "db_table": "sboms_product_cle_support_definitions",
                "unique_together": {("product", "support_id")},
            },
        ),
    ]
