# Generated by Django 5.2.12 on 2026-03-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0053_add_bom_type_discriminator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="component_type",
            field=models.CharField(
                choices=[("sbom", "SBOM"), ("document", "Document"), ("bom", "BOM")],
                default="sbom",
                help_text="Type of component (SBOM, BOM, Document)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="sbom",
            index=models.Index(
                fields=["bom_type", "created_at"], name="sboms_sboms_bom_typ_87e193_idx"
            ),
        ),
    ]
