# Generated by Django 5.2.12 on 2026-04-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0052_remove_componentidentifier"),
        ("sboms", "0053_seed_cle_from_dates"),
    ]

    operations = []
