# Generated by Django 5.2.12 on 2026-04-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_unique_sbom_per_component_release"),
        ("sboms", "0054_merge_20260403_1425"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentCLEEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("released", "Released"),
                            ("endOfDevelopment", "End of Development"),
                            ("endOfSupport", "End of Support"),
                            ("endOfLife", "End of Life"),
                            ("endOfDistribution", "End of Distribution"),
                            ("endOfMarketing", "End of Marketing"),
                            ("supersededBy", "Superseded By"),
                            ("componentRenamed", "Component Renamed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=30,
                    ),
                ),
                ("effective", models.DateTimeField()),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("version", models.CharField(blank=True, default="", max_length=255)),
                ("versions", models.JSONField(blank=True, default=list)),
                (
                    "support_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("license", models.CharField(blank=True, default="", max_length=255)),
                (
                    "superseded_by_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("identifiers", models.JSONField(blank=True, default=list)),
                (
                    "withdrawn_event_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("references", models.JSONField(blank=True, default=list)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cle_events",
                        to="sboms.component",
                    ),
                ),
            ],
            options={
                "db_table": "sboms_component_cle_events",
                "ordering": ["-event_id"],
                "unique_together": {("component", "event_id")},
            },
        ),
        migrations.CreateModel(
            name="ComponentCLESupportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("support_id", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cle_support_definitions",
                        to="sboms.component",
                    ),
                ),
            ],
            options={
                "db_table": "sboms_component_cle_support_definitions",
                "unique_together": {("component", "support_id")},
            },
        ),
        migrations.CreateModel(
            name="ComponentReleaseCLEEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("released", "Released"),
                            ("endOfDevelopment", "End of Development"),
                            ("endOfSupport", "End of Support"),
                            ("endOfLife", "End of Life"),
                            ("endOfDistribution", "End of Distribution"),
                            ("endOfMarketing", "End of Marketing"),
                            ("supersededBy", "Superseded By"),
                            ("componentRenamed", "Component Renamed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=30,
                    ),
                ),
                ("effective", models.DateTimeField()),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("version", models.CharField(blank=True, default="", max_length=255)),
                ("versions", models.JSONField(blank=True, default=list)),
                (
                    "support_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("license", models.CharField(blank=True, default="", max_length=255)),
                (
                    "superseded_by_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("identifiers", models.JSONField(blank=True, default=list)),
                (
                    "withdrawn_event_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("references", models.JSONField(blank=True, default=list)),
                (
                    "component_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cle_events",
                        to="core.componentrelease",
                    ),
                ),
            ],
            options={
                "db_table": "sboms_component_release_cle_events",
                "ordering": ["-event_id"],
                "unique_together": {("component_release", "event_id")},
            },
        ),
        migrations.CreateModel(
            name="ComponentReleaseCLESupportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("support_id", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cle_support_definitions",
                        to="core.componentrelease",
                    ),
                ),
            ],
            options={
                "db_table": "sboms_component_release_cle_support_definitions",
                "unique_together": {("component_release", "support_id")},
            },
        ),
        migrations.CreateModel(
            name="ReleaseCLEEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("released", "Released"),
                            ("endOfDevelopment", "End of Development"),
                            ("endOfSupport", "End of Support"),
                            ("endOfLife", "End of Life"),
                            ("endOfDistribution", "End of Distribution"),
                            ("endOfMarketing", "End of Marketing"),
                            ("supersededBy", "Superseded By"),
                            ("componentRenamed", "Component Renamed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=30,
                    ),
                ),
                ("effective", models.DateTimeField()),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("version", models.CharField(blank=True, default="", max_length=255)),
                ("versions", models.JSONField(blank=True, default=list)),
                (
                    "support_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("license", models.CharField(blank=True, default="", max_length=255)),
                (
                    "superseded_by_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("identifiers", models.JSONField(blank=True, default=list)),
                (
                    "withdrawn_event_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("references", models.JSONField(blank=True, default=list)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cle_events",
                        to="core.release",
                    ),
                ),
            ],
            options={
                "db_table": "sboms_release_cle_events",
                "ordering": ["-event_id"],
                "unique_together": {("release", "event_id")},
            },
        ),
        migrations.CreateModel(
            name="ReleaseCLESupportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("support_id", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cle_support_definitions",
                        to="core.release",
                    ),
                ),
            ],
            options={
                "db_table": "sboms_release_cle_support_definitions",
                "unique_together": {("release", "support_id")},
            },
        ),
    ]
