# Generated by Django 5.2.12 on 2026-04-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0054_add_bom_type_created_at_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="component_type",
            field=models.CharField(
                choices=[("sbom", "SBOM"), ("document", "Document"), ("bom", "BOM")],
                default="sbom",
                help_text="Type of component (SBOM, Document, etc.)",
                max_length=20,
            ),
        ),
    ]
