# Generated by Django 5.2.12 on 2026-04-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0055_simplify_component_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbom",
            name="provenance_blob_key",
            field=models.CharField(
                blank=True,
                help_text="S3 object key for the stored in-toto DSSE provenance envelope",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sbom",
            name="signature_blob_key",
            field=models.CharField(
                blank=True,
                help_text="S3 object key for the stored cryptographic signature",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sbom",
            name="signature_type",
            field=models.CharField(
                blank=True,
                help_text="Signature format: cosign-bundle, pgp-detached, pkcs7",
                max_length=50,
                null=True,
            ),
        ),
    ]
