# Generated by Django 5.2.12 on 2026-04-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0055_add_multi_level_cle_models"),
        ("sboms", "0055_simplify_component_types"),
    ]

    operations = []
