# Generated by Django 5.2.12 on 2026-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0056_merge_20260403_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentclesupportdefinition",
            name="url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="componentreleaseclesupportdefinition",
            name="url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="productclesupportdefinition",
            name="url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="releaseclesupportdefinition",
            name="url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
