# Generated by Django 5.2.12 on 2026-04-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0056_sbom_signature_provenance"),
        ("sboms", "0057_cle_url_max_length_500"),
    ]

    operations = []
