# Generated by Django 5.2.13 on 2026-05-07 10:00

import django.db.models.deletion
import sbomify.apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0058_merge_20260410_1201"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductComponent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sboms.component",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sboms.product"
                    ),
                ),
            ],
            options={
                "db_table": "sboms_products_components",
            },
        ),
        migrations.AddField(
            model_name="component",
            name="products",
            field=models.ManyToManyField(
                related_name="components",
                through="sboms.ProductComponent",
                to="sboms.product",
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponent",
            index=models.Index(
                fields=["product", "component"], name="sboms_produ_product_154d10_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productcomponent",
            unique_together={("product", "component")},
        ),
    ]
