"""Backfill ``ProductComponent`` from the existing ``Product → Project → Component`` chain.

For every (product, component) pair reachable through ``ProductProject ⨝ ProjectComponent``
**where the product and the component belong to the same team**, insert a
``ProductComponent`` row. Cross-team pairs (which should not exist but historically were
not enforced) are skipped — propagating them would violate the new tenancy invariant
guarded by ``ProductComponent.clean()`` and the ``reject_cross_tenant_product_component_links``
signal receiver.

``unique_together("product", "component")`` plus ``bulk_create(..., ignore_conflicts=True)``
provide dedup — duplicate inserts (same component reachable through multiple projects under
the same product) are silently dropped at the DB level, so the migration code does not need
to track seen pairs.

Reverse is intentionally a no-op: the legacy join tables still exist after this migration,
so the data is recoverable until ``0062_remove_product_projects_remove_project_products_and_more``
(the destructive drop of ``Product.projects`` / ``Component.projects`` and the ``Project`` /
``ProductProject`` / ``ProjectComponent`` models) runs.
"""

from __future__ import annotations

from typing import Any

from django.db import migrations

# Cap memory at ~16k rows in flight regardless of vendor — large enough that the
# bulk_create round-trip dominates wall time, small enough that we never hold a
# meaningful fraction of a tenant's link table in Python at once.
_FETCH_BATCH = 2000
_INSERT_BATCH = 2000


def forwards(apps: Any, schema_editor: Any) -> None:
    """Backfill ``sboms_products_components`` from the legacy chain.

    Two code paths, with different memory profiles by design:

      - **Postgres (production)**: bounded memory. The join is computed by the
        database via a single ``SELECT DISTINCT`` over
        ``ProductProject ⨝ ProjectComponent`` that also inner-joins
        ``sboms_products`` and ``sboms_components`` on ``team_id`` so
        cross-tenant pairs are filtered server-side. Rows are streamed in
        ``_FETCH_BATCH`` chunks via ``cursor.fetchmany()`` and inserted in
        ``_INSERT_BATCH`` chunks via ``bulk_create(ignore_conflicts=True)``.
        Each insert batch commits in its own short transaction so we never
        hold an exclusive lock on ``sboms_products_components`` for the whole
        backfill.

      - **SQLite (tests only)**: NOT bounded memory. The fallback materialises
        full ``product_id → team_id`` and ``component_id → team_id`` lookup
        dicts plus a ``project_id → [product_id...]`` index in Python. This
        is acceptable because the only realistic caller is the migration test
        suite running against tiny fixtures (a handful of rows). Production
        databases are always Postgres; if that assumption ever changes (e.g.
        a new supported vendor), this branch needs to be reworked into a
        batched lookup or the docstring updated to reflect that vendor's
        characteristics.

    IDs are generated by ``generate_id`` (12-char alphanum, the project
    convention); a raw set-based ``INSERT ... SELECT`` was rejected because
    Postgres has no equivalent of ``generate_id`` available without a custom
    SQL function, and the per-batch ``bulk_create`` cost is negligible at
    realistic tenant sizes.
    """
    from django.db import connection, transaction

    from sbomify.apps.core.utils import generate_id

    ProductComponent = apps.get_model("sboms", "ProductComponent")
    ProductProject = apps.get_model("sboms", "ProductProject")
    ProjectComponent = apps.get_model("sboms", "ProjectComponent")
    Product = apps.get_model("sboms", "Product")
    Component = apps.get_model("sboms", "Component")

    pp_table = ProductProject._meta.db_table
    pjc_table = ProjectComponent._meta.db_table
    p_table = Product._meta.db_table
    c_table = Component._meta.db_table

    batch: list[Any] = []

    def _flush() -> None:
        if not batch:
            return
        with transaction.atomic():
            ProductComponent.objects.bulk_create(batch, ignore_conflicts=True)
        batch.clear()

    if connection.vendor == "postgresql":
        # The DB does the cross-product expansion AND the same-team filter.
        # `SELECT DISTINCT` collapses the duplicates that arise when a
        # component is reachable via multiple projects under the same product.
        sql = f"""
            SELECT DISTINCT pp.product_id, pjc.component_id
            FROM {pp_table} pp
            JOIN {pjc_table} pjc ON pjc.project_id = pp.project_id
            JOIN {p_table} p ON p.id = pp.product_id
            JOIN {c_table} c ON c.id = pjc.component_id
            WHERE p.team_id = c.team_id
        """
        with connection.cursor() as cursor:
            cursor.execute(sql)
            while True:
                rows = cursor.fetchmany(_FETCH_BATCH)
                if not rows:
                    break
                for product_id, component_id in rows:
                    batch.append(ProductComponent(id=generate_id(), product_id=product_id, component_id=component_id))
                    if len(batch) >= _INSERT_BATCH:
                        _flush()
        _flush()
    elif connection.vendor == "sqlite":
        # SQLite (tests only): drive the join with ORM iterators and a small
        # in-memory lookup. The same cross-tenant filter applies. This path
        # materialises Product/Component team mappings in Python and is NOT
        # safe for very large workspaces — it is restricted to SQLite so a
        # future deploy against MySQL/Oracle/etc. fails loudly rather than
        # silently running the slow path against a production-scale dataset.
        product_team_by_id: dict[str, str] = dict(
            Product.objects.values_list("id", "team_id").iterator(chunk_size=_FETCH_BATCH)
        )
        component_team_by_id: dict[str, str] = dict(
            Component.objects.values_list("id", "team_id").iterator(chunk_size=_FETCH_BATCH)
        )

        pp_by_project: dict[str, list[str]] = {}
        for prod_id, proj_id in ProductProject.objects.values_list("product_id", "project_id").iterator(
            chunk_size=_FETCH_BATCH
        ):
            pp_by_project.setdefault(proj_id, []).append(prod_id)

        for proj_id, comp_id in ProjectComponent.objects.values_list("project_id", "component_id").iterator(
            chunk_size=_FETCH_BATCH
        ):
            comp_team = component_team_by_id.get(comp_id)
            if comp_team is None:
                continue
            for prod_id in pp_by_project.get(proj_id, ()):
                if product_team_by_id.get(prod_id) != comp_team:
                    continue
                batch.append(ProductComponent(id=generate_id(), product_id=prod_id, component_id=comp_id))
                if len(batch) >= _INSERT_BATCH:
                    _flush()
        _flush()
    else:
        raise NotImplementedError(
            f"Backfill not implemented for database vendor {connection.vendor!r}. "
            "Add a vendor-specific path before running this migration."
        )


class Migration(migrations.Migration):
    # The backfill is a long-running data migration; running it inside a single
    # transaction holds an exclusive lock on sboms_products_components for the
    # whole operation, blocking writes during a rolling deploy. Mark non-atomic
    # so each `_flush()` commits independently (see `forwards`).
    atomic = False

    dependencies = [
        ("sboms", "0059_add_productcomponent"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
