# Generated by Django 5.2.13 on 2026-05-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0060_backfill_productcomponent"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productcomponent",
            name="sboms_produ_product_154d10_idx",
        ),
    ]
