# Generated by Django 5.2.13 on 2026-05-07 13:36
#
# Phase 7 destructive migration: drop the Project layer.
#
# This migration also performs a one-time visibility demotion (in `forwards`)
# to preserve the listing semantics that existed before the cascade change.
# Pre-PR, a component was listed on the trust center only if its parent
# project was also `is_public=True`. After this PR, the cascade is just
# `Product.is_public AND Component.visibility ∈ {PUBLIC, GATED}`. Components
# that were soft-hidden by `Project.is_public=False` would otherwise surface
# automatically the moment this migration runs. The demotion converts those
# components to PRIVATE so the previous tenant-controlled hiding behaviour is
# preserved through the schema change.

from __future__ import annotations

from typing import Any

from django.db import migrations


def demote_visibility_for_previously_hidden_components(apps: Any, schema_editor: Any) -> None:
    """Demote `Component.visibility` from PUBLIC/GATED to PRIVATE for any
    component whose pre-PR public listing depended on a `Project.is_public`
    gate that this migration is about to remove.

    A component is "newly visible" (and therefore demoted) iff:
      - `visibility` is PUBLIC or GATED
      - it is linked to at least one product where `is_public=True`
      - no project containing the component is itself `is_public=True`
        with at least one public product attached

    The demotion runs as the first operation of this migration, so the
    `projects` reverse relation is still available on the historical model
    state.
    """
    Component = apps.get_model("sboms", "Component")
    PUBLIC = "public"
    GATED = "gated"
    PRIVATE = "private"

    candidates = Component.objects.filter(
        visibility__in=(PUBLIC, GATED),
        products__is_public=True,
    ).distinct()

    already_visible = Component.objects.filter(
        visibility__in=(PUBLIC, GATED),
        projects__is_public=True,
        projects__products__is_public=True,
    ).values_list("id", flat=True)
    already_visible_ids = set(already_visible)

    demote_ids = [c.id for c in candidates if c.id not in already_visible_ids]
    if demote_ids:
        Component.objects.filter(id__in=demote_ids).update(visibility=PRIVATE)


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0061_remove_productcomponent_sboms_produ_product_154d10_idx"),
        # Drop the core proxy models for Project/ProductProject/ProjectComponent
        # before this migration removes the concrete sboms models that backed them.
        # Either order works at the SQL level (proxies have no tables), but making
        # the dependency explicit prevents Django from picking the unsafe order
        # under future graph rewrites.
        ("core", "0026_delete_productproject_delete_project_and_more"),
    ]

    operations = [
        migrations.RunPython(
            demote_visibility_for_previously_hidden_components,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="product",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="project",
            name="products",
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="project",
            name="components",
        ),
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.RemoveField(
            model_name="component",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="projectcomponent",
            name="project",
        ),
        migrations.AlterUniqueTogether(
            name="projectcomponent",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="projectcomponent",
            name="component",
        ),
        migrations.DeleteModel(
            name="ProductProject",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectComponent",
        ),
    ]
