# Generated by Django 5.2.13 on 2026-05-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0061_remove_productcomponent_sboms_produ_product_154d10_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="project",
            name="products",
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="project",
            name="components",
        ),
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.RemoveField(
            model_name="component",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="projectcomponent",
            name="project",
        ),
        migrations.AlterUniqueTogether(
            name="projectcomponent",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="projectcomponent",
            name="component",
        ),
        migrations.DeleteModel(
            name="ProductProject",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectComponent",
        ),
    ]
