# Generated by Django 5.2.13 on 2026-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0062_remove_product_projects_remove_project_products_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productcomponent",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="productcomponent",
            constraint=models.UniqueConstraint(
                fields=("product", "component"), name="sboms_productcomponent_unique"
            ),
        ),
    ]
