# Generated by Django 5.2.13 on 2026-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0063_alter_productcomponent_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="Workspace-scoped component: not attached to any product. Only DOCUMENT components may be global; setting this clears any existing product attachments on save.",
            ),
        ),
    ]
