# Generated by Django 5.2.14 on 2026-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sboms",
            "0065_remove_sbom_sboms_sbom_unique_component_version_format_qualifiers_bom_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sbom",
            name="has_crypto_assets",
            field=models.BooleanField(
                default=None,
                help_text="Whether the document contains cryptographic-asset components, computed at upload. None means unknown (rows predating the field); crypto-gated assessments run for True and None, and skip dispatch for False.",
                null=True,
            ),
        ),
    ]
