# Generated by Django 5.2.14 on 2026-07-28 10:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import sbomify.apps.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("sboms", "0066_sbom_has_crypto_assets"),
        ("teams", "0037_invitation_invitation_role_not_bot"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubProcessor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The vendor's name, e.g. Amazon Web Services",
                        max_length=255,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What they do for you, e.g. Hosting",
                        max_length=255,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where processing happens",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ManyToManyField(blank=True, related_name="sub_processors", to="sboms.product"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_processors",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "sboms_sub_processors",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["team"], name="sboms_subproc_team_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "name"),
                        name="sboms_sub_processor_unique_name_per_team",
                    )
                ],
            },
        ),
    ]
