# Generated by Django 5.2.14 on 2026-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0066_sbom_has_crypto_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="sbom_freshness_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Overrides the workspace freshness window for this component. Empty inherits the workspace setting.",
                null=True,
            ),
        ),
    ]
