# Generated by Django 5.2.17 on 2026-08-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0067_component_sbom_freshness_days"),
        (
            "teams",
            "0042_rename_teams_invit_email_d19291_idx_workspaces__email_77ed9e_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="component",
            new_name="sboms_compo_workspa_3edbe9_idx",
            old_name="sboms_compo_team_id_fe2066_idx",
        ),
        migrations.RenameIndex(
            model_name="component",
            new_name="sboms_compo_workspa_cf9816_idx",
            old_name="sboms_compo_team_id_b000be_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="sboms_produ_workspa_3b1766_idx",
            old_name="sboms_produ_team_id_c11cd4_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="sboms_produ_workspa_b360b4_idx",
            old_name="sboms_produ_team_id_071f2b_idx",
        ),
        migrations.AlterField(
            model_name="component",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="productidentifier",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="productlink",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
    ]
