# Generated by Django 5.2.14 on 2026-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0067_component_sbom_freshness_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbom",
            name="has_hardware_components",
            field=models.BooleanField(
                default=None,
                help_text="Whether the document contains device components, computed at upload. None means unknown (rows predating the field); hardware-gated work runs for True and None, and skips dispatch for False — except for a document explicitly tagged bom_type=hbom, which dispatches whatever this says, so a generator that emits no device components is reported rather than skipped.",
                null=True,
            ),
        ),
    ]
