# Generated by Django 5.2.14 on 2026-08-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0069_alter_sbom_has_hardware_components"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sbom",
            name="has_hardware_components",
            field=models.BooleanField(
                default=None,
                help_text="Whether the document names a device component, in components[] or as the metadata component, computed at upload. None means unknown (rows predating the field); hardware-gated work runs for True and None, and skips dispatch for False — except for a document explicitly tagged bom_type=hbom, which dispatches whatever this says, so a generator that emits no device components is reported rather than skipped.",
                null=True,
            ),
        ),
    ]
