# Generated by Django 5.2.6 on 2025-10-13 08:49

import django.db.models.deletion
import sbomify.apps.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingStatus",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "has_created_component",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has created their first component",
                    ),
                ),
                (
                    "first_component_created_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user created their first component",
                        null=True,
                    ),
                ),
                (
                    "has_uploaded_sbom",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has uploaded their first SBOM",
                    ),
                ),
                (
                    "first_sbom_uploaded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user uploaded their first SBOM",
                        null=True,
                    ),
                ),
                (
                    "has_completed_wizard",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has completed the onboarding wizard",
                    ),
                ),
                (
                    "wizard_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user completed the onboarding wizard",
                        null=True,
                    ),
                ),
                (
                    "welcome_email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the welcome email has been sent",
                    ),
                ),
                (
                    "welcome_email_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the welcome email was sent",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Status",
                "verbose_name_plural": "Onboarding Statuses",
                "db_table": "onboarding_onboardingstatus",
            },
        ),
        migrations.CreateModel(
            name="OnboardingEmail",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome"),
                            ("first_component_sbom", "First Component/SBOM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Email",
                "verbose_name_plural": "Onboarding Emails",
                "db_table": "onboarding_onboardingemail",
                "unique_together": {("user", "email_type")},
            },
        ),
    ]
