# Generated by Django 5.2.7 on 2026-01-05 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_remove_onboardingemail_success_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="onboardingstatus",
            index=models.Index(
                fields=["has_completed_wizard"], name="onboarding__has_com_62b3b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingstatus",
            index=models.Index(
                fields=["has_created_component"], name="onboarding__has_cre_b4ab39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingstatus",
            index=models.Index(
                fields=["has_uploaded_sbom"], name="onboarding__has_upl_59130e_idx"
            ),
        ),
    ]
