# Generated by Django 5.2.7 on 2026-02-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0003_onboardingstatus_onboarding__has_com_62b3b2_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingemail",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome"),
                    ("quick_start", "Quick Start Guide"),
                    ("first_component", "First Component"),
                    ("first_sbom", "First SBOM"),
                    ("collaboration", "Team Collaboration"),
                    ("first_component_sbom", "First Component/SBOM"),
                ],
                max_length=50,
            ),
        ),
    ]
