# Generated by Django 5.2.13 on 2026-05-06 10:30

from django.db import migrations, models
from django.utils import timezone


def backfill_drip_started_at(apps, schema_editor):
    """Reset the drip clock to deploy time for backlog welcome-emailed users.

    Scoped to rows where `welcome_email_sent=True AND drip_started_at IS NULL`
    — the only cohort that would otherwise hit every drip threshold
    simultaneously when the scheduler comes online for the first time.
    Users who haven't received the welcome email yet are skipped so they
    enter the campaign normally once welcome fires.

    With `drip_started_at` reset to now, each backlog user goes through the
    full sequence (day 1, 3, 7, 10) over the next ~10 days, rather than
    receiving every email simultaneously because they've passed every
    threshold via signup-anchored eligibility.
    """
    OnboardingStatus = apps.get_model("onboarding", "OnboardingStatus")
    OnboardingStatus.objects.filter(
        welcome_email_sent=True,
        drip_started_at__isnull=True,
    ).update(drip_started_at=timezone.now())


def reverse_backfill(apps, schema_editor):
    """Reverse no-op — there's no meaningful previous state to restore."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0004_alter_onboardingemail_email_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingstatus",
            name="drip_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the onboarding drip campaign clock started for this user",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_drip_started_at, reverse_backfill),
    ]
