# Generated by Django 5.2.17 on 2026-08-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0006_remove_first_component_sbom_email_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingstatus",
            name="drip_unsubscribed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user unsubscribed from onboarding emails",
                null=True,
            ),
        ),
    ]
