# Generated by Django 5.2.14 on 2026-05-20 10:37

import django.db.models.deletion
import sbomify.apps.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sboms", "0064_alter_component_is_global"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OIDCBinding",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub Actions")],
                        default="github",
                        max_length=32,
                    ),
                ),
                (
                    "repository",
                    models.CharField(
                        help_text="External repository identifier for DISPLAY only. GitHub: 'org/repo' (case-insensitive, stored lowercase). Matching uses the immutable IDs below; this string may go stale after a rename.",
                        max_length=255,
                    ),
                ),
                (
                    "repository_id",
                    models.BigIntegerField(
                        help_text="GitHub's immutable numeric repository ID. The token-exchange endpoint matches incoming tokens against this, NEVER the name."
                    ),
                ),
                (
                    "repository_owner_id",
                    models.BigIntegerField(
                        help_text="GitHub's immutable numeric owner (user/org) ID. Matched alongside ``repository_id`` to defeat account-resurrection attacks."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Updated each time a token is issued. Lets admins prune stale bindings.",
                        null=True,
                    ),
                ),
                (
                    "bot_user",
                    models.OneToOneField(
                        help_text="Synthetic bot identity for this binding. Created in the same transaction as the binding via ``services.provision_bot_user_for_binding``. Cleanup is asymmetric: ``on_delete=CASCADE`` runs when the User is deleted (it removes this binding row), NOT when the binding is deleted — for binding → bot cleanup we rely on the ``cleanup_bot_user_on_binding_delete`` post_delete signal in ``signals.py``. Nullable solely to support the two-phase create flow in ``services.create_binding``: the binding is INSERTed first to get a stable ``id`` (used to derive the bot username), then the bot is provisioned and the FK is attached. Outside that ~µs window inside the create transaction the column is always non-null.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_binding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_bindings",
                        to="sboms.component",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The Workspace member who set up this binding (audit).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "oidc_bindings",
                "indexes": [
                    models.Index(
                        fields=["provider", "repository_owner_id", "repository_id"],
                        name="oidc_binding_provider_ids_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "component",
                            "provider",
                            "repository_owner_id",
                            "repository_id",
                        ),
                        name="oidc_binding_unique_per_component_repo_ids",
                    )
                ],
            },
        ),
    ]
