# Generated by Django 5.2.14 on 2026-06-02 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0001_initial"),
        ("sboms", "0064_alter_component_is_global"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="oidcbinding",
            name="oidc_binding_unique_per_component_repo_ids",
        ),
        migrations.AlterField(
            model_name="oidcbinding",
            name="repository",
            field=models.CharField(
                help_text="External repository identifier. GitHub: 'org/repo' (case-insensitive, stored lowercase). Used to match a still-UNPINNED binding on the first exchange; once the IDs below are pinned, matching is by ID and this string is display-only (may go stale after a rename).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="oidcbinding",
            name="repository_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="GitHub's immutable numeric repository ID. NULL until pinned. Resolved at create time for public repos; for private repos (sbomify can't read their metadata anonymously) it stays NULL and is pinned from the first signed OIDC token at exchange. Once set, the exchange matches on this, NEVER the name.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="oidcbinding",
            name="repository_owner_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="GitHub's immutable numeric owner (user/org) ID. NULL until pinned (see ``repository_id``). Matched alongside ``repository_id`` to defeat account-resurrection attacks.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="oidcbinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("repository_id__isnull", True),
                        ("repository_owner_id__isnull", True),
                    ),
                    models.Q(
                        ("repository_id__isnull", False),
                        ("repository_owner_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="oidc_binding_ids_both_or_neither",
            ),
        ),
        migrations.AddConstraint(
            model_name="oidcbinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("repository_id__isnull", True),
                    ("repository_owner_id__isnull", True),
                ),
                fields=("component", "provider", "repository"),
                name="oidc_binding_unique_unpinned_repo_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="oidcbinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("repository_id__isnull", False),
                    ("repository_owner_id__isnull", False),
                ),
                fields=(
                    "component",
                    "provider",
                    "repository_owner_id",
                    "repository_id",
                ),
                name="oidc_binding_unique_pinned_repo_ids",
            ),
        ),
    ]
