# Generated by Django 5.2.14 on 2026-05-20 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0001_initial"),
        ("sboms", "0064_alter_component_is_global"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="oidcbinding",
            name="oidc_binding_unique_per_component_repo",
        ),
        migrations.RemoveIndex(
            model_name="oidcbinding",
            name="oidc_binding_provider_repo_idx",
        ),
        # The default=0 sentinel exists only to satisfy AddField when the
        # oidc_bindings table is empty (which it is in every environment —
        # this is a brand-new model). preserve_default=False prevents the
        # default from leaking into the model state, so the resulting field
        # matches the no-default model definition.
        migrations.AddField(
            model_name="oidcbinding",
            name="repository_id",
            field=models.BigIntegerField(
                default=0,
                help_text="GitHub's immutable numeric repository ID. The token-exchange endpoint matches incoming tokens against this, NEVER the name.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="oidcbinding",
            name="repository_owner_id",
            field=models.BigIntegerField(
                default=0,
                help_text="GitHub's immutable numeric owner (user/org) ID. Matched alongside ``repository_id`` to defeat account-resurrection attacks.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="oidcbinding",
            name="repository",
            field=models.CharField(
                help_text="External repository identifier for DISPLAY only. GitHub: 'org/repo' (case-insensitive, stored lowercase). Matching uses the immutable IDs below; this string may go stale after a rename.",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="oidcbinding",
            index=models.Index(
                fields=["provider", "repository_owner_id", "repository_id"],
                name="oidc_binding_provider_ids_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="oidcbinding",
            constraint=models.UniqueConstraint(
                fields=(
                    "component",
                    "provider",
                    "repository_owner_id",
                    "repository_id",
                ),
                name="oidc_binding_unique_per_component_repo_ids",
            ),
        ),
    ]
