# Generated by Django 5.2.12 on 2026-03-25 18:00

import django.db.models.deletion
import sbomify.apps.core.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0025_unique_sbom_per_component_release"),
        ("teams", "0032_populate_team_slugs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlCatalog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                (
                    "source",
                    models.CharField(
                        choices=[("builtin", "Built-in"), ("custom", "Custom")],
                        default="builtin",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_catalogs",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "controls_catalog",
                "ordering": ["-created_at"],
                "unique_together": {("team", "name", "version")},
            },
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group", models.CharField(max_length=255)),
                ("control_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="controls.controlcatalog",
                    ),
                ),
            ],
            options={
                "db_table": "controls_control",
                "ordering": ["sort_order", "control_id"],
                "unique_together": {("catalog", "control_id")},
            },
        ),
        migrations.CreateModel(
            name="ControlStatus",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("partial", "Partial"),
                            ("not_implemented", "Not Implemented"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_implemented",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="controls.control",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_statuses",
                        to="core.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "controls_status",
                "ordering": ["control__sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("product__isnull", False)),
                        fields=("control", "product"),
                        name="unique_control_product",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("product__isnull", True)),
                        fields=("control",),
                        name="unique_control_global",
                    ),
                ],
            },
        ),
    ]
