# Generated by Django 5.2.17 on 2026-08-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0004_add_control_evidence"),
        (
            "teams",
            "0042_rename_teams_invit_email_d19291_idx_workspaces__email_77ed9e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlcatalog",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="control_catalogs",
                to="teams.team",
            ),
        ),
    ]
