# Generated by Django 5.2.17 on 2026-09-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0005_alter_controlcatalog_team"),
        ("teams", "0043_team_publish_vulnerability_posture"),
    ]

    operations = [
        migrations.AddField(
            model_name="control",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="controlcatalog",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="controlcatalog",
            name="source",
            field=models.CharField(
                choices=[
                    ("builtin", "Built-in"),
                    ("custom", "Custom"),
                    ("vanta", "Vanta"),
                ],
                default="builtin",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="controlcatalog",
            index=models.Index(
                fields=["team", "source", "external_id"],
                name="controls_catalog_source_idx",
            ),
        ),
    ]
