# Generated by Django 5.2.17 on 2026-09-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    """Split "the workspace tracks this framework" from "the public sees it".

    ``is_active`` meant both until now, and nothing rendered the public side,
    so no workspace has ever had a catalogue of theirs appear on a trust
    center. Defaulting the new flag to False keeps it that way: an existing
    workspace tracking SOC 2 internally does not start publishing a compliance
    score to its customers because this deployed.
    """


    dependencies = [
        ("controls", "0006_add_external_source_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlcatalog",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
