# Generated by Django 5.2.17 on 2026-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0007_add_controlcatalog_is_published"),
        ("teams", "0043_team_publish_vulnerability_posture"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="controlcatalog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("team", "source", "external_id"),
                name="unique_catalog_per_external_id",
            ),
        ),
    ]
