import 'vite/modulepreload-polyfill';
import '../../core/js/layout-interactions';
import { registerTeamBranding, registerCustomDomain } from './team-branding';
import { registerConfirmModal } from '../../core/js/components/confirm-modal';
import { registerCopyableValue } from '../../core/js/components/copyable-value';
import { registerFileDragAndDrop } from '../../core/js/components/file-drag-and-drop';
import { registerWorkspaceSwitcher } from '../../core/js/components/workspace-switcher';
import { registerSiteNotifications } from '../../core/js/components/site-notifications';
import { registerOnboardingWizard } from './onboarding-wizard';
import { registerTeamGeneral } from './team-general';
import { initializeAlpine } from '../../core/js/alpine-init';

registerConfirmModal();
registerCopyableValue();
registerFileDragAndDrop();
registerWorkspaceSwitcher();
registerSiteNotifications();
registerTeamBranding();
registerCustomDomain();
registerOnboardingWizard();
registerTeamGeneral();
initializeAlpine();
