# Generated by Django 5.2.3 on 2025-06-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_fix_contenttype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={"managed": True, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"managed": True, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="productproject",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"managed": True, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="projectcomponent",
            options={"managed": True},
        ),
    ]
