# Generated by Django 5.2.3 on 2025-06-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_component_options_alter_product_options_and_more"),
        ("teams", "0014_update_team_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="component_type",
            field=models.CharField(
                choices=[("sbom", "SBOM")], default="sbom", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="projects",
            field=models.ManyToManyField(
                through="catalog.ProjectComponent", to="catalog.project"
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_components",
                to="teams.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="projects",
            field=models.ManyToManyField(
                through="catalog.ProductProject", to="catalog.project"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_products",
                to="teams.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productproject",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productproject",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="components",
            field=models.ManyToManyField(
                through="catalog.ProjectComponent", to="catalog.component"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="products",
            field=models.ManyToManyField(
                through="catalog.ProductProject", to="catalog.product"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_projects",
                to="teams.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectcomponent",
            name="component",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.component",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectcomponent",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("team", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("team", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="productproject",
            unique_together={("product", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("team", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="projectcomponent",
            unique_together={("project", "component")},
        ),
    ]
