# Generated by Django 5.2.3 on 2025-06-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_ensure_tables_and_add_fields"),
        ("teams", "0014_update_team_keys"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("team", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("team", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="productproject",
            unique_together={("product", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("team", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="projectcomponent",
            unique_together={("project", "component")},
        ),
    ]
