# Generated by Django 5.0.4 on 2024-06-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0004_alter_sbom_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sbom",
            unique_together=set(),
        ),
    ]
