# Generated by Django 5.0.4 on 2024-07-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0006_sbom_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbom",
            name="format",
            field=models.CharField(default="spdx", max_length=255),
        ),
    ]
