# Generated by Django 5.0.4 on 2024-07-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0007_sbom_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="name",
            field=models.CharField(default="not-set", max_length=255),
        ),
        migrations.AddField(
            model_name="package",
            name="version",
            field=models.CharField(default="not-set", max_length=255),
        ),
    ]
