# Generated by Django 5.0.4 on 2024-07-08 23:40
# Data migration for setting package fields (added in 0008) to proper values.

from django.db import migrations


def set_package_fields(apps, schema_editor):
    Package = apps.get_model("sboms", "Package")
    for package in Package.objects.all():
        package_dict = package.data
        package.name = package_dict.get("name", "")
        package.version = package_dict.get("versionInfo", "")
        package.license_name = package_dict.get("licenseConcluded", "")
        package.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0008_package_name_package_version"),
    ]

    operations = [
        migrations.RunPython(set_package_fields),
    ]
