# Generated by Django 5.0.4 on 2024-07-16 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0010_remove_exiting_sbom_and_project_records"),
        ("teams", "0003_invitation_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sbom",
            name="project",
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sboms.project"
                    ),
                ),
            ],
            options={
                "db_table": "sboms_components",
                "unique_together": {("project", "name", "version")},
            },
        ),
        migrations.AddField(
            model_name="sbom",
            name="component",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sboms.component"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="teams.team"),
                ),
            ],
            options={
                "db_table": "sboms_products",
                "unique_together": {("team", "name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="project",
            name="product",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sboms.product"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("product", "name")},
        ),
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
    ]
