# Generated by Django 5.0.4 on 2024-07-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0011_remove_sbom_project_component_sbom_component_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sbom",
            name="is_public",
        ),
        migrations.AddField(
            model_name="component",
            name="is_public",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(null=True),
        ),
    ]
