# Generated by Django 5.0.4 on 2024-07-26 06:03

import django.db.models.deletion
from django.db import migrations, models


def add_dummy_team(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    team = Team.objects.create(id=-1, name="Dummy Team")
    team.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0012_remove_sbom_is_public_component_is_public_and_more"),
        ("teams", "0003_invitation_expires_at"),
    ]

    operations = [
        migrations.RunPython(add_dummy_team),
        migrations.AddField(
            model_name="component",
            name="team",
            field=models.ForeignKey(
                default=-1, on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                default=-1, on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
            preserve_default=False,
        ),
    ]
