# Generated by Django 5.0.4 on 2024-07-26 06:05

from django.db import migrations


def set_project_team(apps, schema_editor):
    Project = apps.get_model("sboms", "Project")
    for project in Project.objects.all():
        project.team = project.product.team
        project.save()


def set_component_team(apps, schema_editor):
    Component = apps.get_model("sboms", "Component")
    for component in Component.objects.all():
        component.team = component.project.team
        component.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0013_component_team_project_team"),
    ]

    operations = [
        migrations.RunPython(set_project_team),
        migrations.RunPython(set_component_team),
    ]
