# Generated by Django 5.0.4 on 2024-07-26 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0014_set_project_and_component_team"),
        ("teams", "0003_invitation_expires_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("team", "name", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("team", "name")},
        ),
        migrations.CreateModel(
            name="ProductProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sboms.product"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sboms.project"
                    ),
                ),
            ],
            options={
                "db_table": "sboms_products_packages",
                "unique_together": {("product", "project")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="projects",
            field=models.ManyToManyField(through="sboms.ProductProject", to="sboms.project"),
        ),
        migrations.AddField(
            model_name="project",
            name="products",
            field=models.ManyToManyField(through="sboms.ProductProject", to="sboms.product"),
        ),
        migrations.CreateModel(
            name="ProjectComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sboms.component"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sboms.project"
                    ),
                ),
            ],
            options={
                "db_table": "sboms_projects_components",
                "unique_together": {("project", "component")},
            },
        ),
        migrations.AddField(
            model_name="component",
            name="projects",
            field=models.ManyToManyField(through="sboms.ProjectComponent", to="sboms.project"),
        ),
        migrations.AddField(
            model_name="project",
            name="components",
            field=models.ManyToManyField(through="sboms.ProjectComponent", to="sboms.component"),
        ),
        migrations.RemoveField(
            model_name="component",
            name="project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="product",
        ),
    ]
