# Generated by Django 5.1 on 2024-09-07 03:05

import ruid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sboms', '0020_switch_to_ruids'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='projects',
            field=models.ManyToManyField(through='sboms.ProjectComponent', to='sboms.project'),
        ),
        migrations.AddField(
            model_name='product',
            name='projects',
            field=models.ManyToManyField(through='sboms.ProductProject', to='sboms.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='components',
            field=models.ManyToManyField(through='sboms.ProjectComponent', to='sboms.component'),
        ),
        migrations.AddField(
            model_name='project',
            name='products',
            field=models.ManyToManyField(through='sboms.ProductProject', to='sboms.product'),
        ),
        migrations.AddField(
            model_name='sbom',
            name='packages',
            field=models.ManyToManyField(through='sboms.SBOMPackage', to='sboms.package'),
        ),
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.CharField(default=ruid.ruid, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=ruid.ruid, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productproject',
            name='id',
            field=models.CharField(default=ruid.ruid, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=ruid.ruid, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectcomponent',
            name='id',
            field=models.CharField(default=ruid.ruid, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sbom',
            name='id',
            field=models.CharField(default=ruid.ruid, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sbompackage',
            name='id',
            field=models.CharField(default=ruid.ruid, max_length=20, primary_key=True, serialize=False),
        ),
    ]
