# Generated by Django 5.1 on 2024-09-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sboms', '0021_component_projects_product_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbom',
            name='format_version',
            field=models.CharField(default='', max_length=20),
        ),
    ]
