# Generated by Django 5.1 on 2024-09-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sboms', '0022_sbom_format_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbom',
            name='packages',
        ),
        migrations.AlterUniqueTogether(
            name='sbompackage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sbompackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='sbompackage',
            name='sbom',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='SBOMPackage',
        ),
    ]
