# Generated by Django 5.2.1 on 2025-05-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0029_alter_component_id_alter_product_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sbom",
            name="licenses",
        ),
        migrations.RemoveField(
            model_name="sbom",
            name="packages_licenses",
        ),
    ]
