# Generated by Django 5.1.4 on 2025-05-19 15:53

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0029_alter_component_id_alter_product_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseComponent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=20)),
                ("is_spdx", models.BooleanField(default=False)),
                ("is_recognized", models.BooleanField(default=False)),
                ("is_deprecated", models.BooleanField(default=False)),
                ("is_osi_approved", models.BooleanField(default=False)),
                ("is_fsf_approved", models.BooleanField(default=False)),
                ("url", models.URLField(null=True)),
                ("text", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sboms_license_components",
                "ordering": ["identifier"],
            },
        ),
        migrations.CreateModel(
            name="LicenseExpression",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operator", models.CharField(blank=True, max_length=10, null=True)),
                ("expression", models.TextField()),
                ("normalized_expression", models.TextField()),
                ("source", models.CharField(max_length=50)),
                ("validation_status", models.CharField(max_length=20)),
                ("validation_errors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sboms.licensecomponent",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="sboms.licenseexpression",
                    ),
                ),
            ],
            options={
                "db_table": "sboms_license_expressions",
                "ordering": ["-created_at"],
            },
        ),
    ]
