# Generated by Django 5.2.3 on 2025-06-30 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_component_options_alter_product_options_and_more"),
        ("sboms", "0030_remove_sbom_licenses_remove_sbom_packages_licenses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="components",
        ),
        migrations.AlterField(
            model_name="sbom",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.component"
            ),
        ),
        migrations.RemoveField(
            model_name="projectcomponent",
            name="component",
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="product",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="product",
            name="team",
        ),
        migrations.RemoveField(
            model_name="project",
            name="products",
        ),
        migrations.RemoveField(
            model_name="productproject",
            name="product",
        ),
        migrations.AlterUniqueTogether(
            name="productproject",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productproject",
            name="project",
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.RemoveField(
            model_name="projectcomponent",
            name="project",
        ),
        migrations.AlterUniqueTogether(
            name="projectcomponent",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Component",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductProject",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectComponent",
        ),
        migrations.CreateModel(
            name="Component",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.component",),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="ProductProject",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.productproject",),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.project",),
        ),
        migrations.CreateModel(
            name="ProjectComponent",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.projectcomponent",),
        ),
    ]
