# Generated by Django 5.2.3 on 2025-06-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0032_validate_data_integrity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Component",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductProject",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectComponent",
        ),
    ]
