# Generated by Django 5.2.4 on 2025-07-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0035_migrate_component_metadata_to_native_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional product description"
            ),
        ),
    ]
