# Generated by Django 5.2.3 on 2025-07-09 09:23

import sbomify.apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_component_product_productproject_project_and_more"),
        ("documents", "0002_alter_document_document_type"),
        ("sboms", "0034_add_product_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Release name (e.g., 'v1.0.0', 'latest')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional release description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_latest",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default 'latest' release that auto-updates with new artifacts",
                    ),
                ),
                (
                    "is_prerelease",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a pre-release version (alpha, beta, RC, etc.)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "db_table": "core_releases",
                "ordering": ["-created_at"],
                "unique_together": {("product", "name")},
            },
        ),
        migrations.CreateModel(
            name="ReleaseArtifact",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document artifact included in this release",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="core.release",
                    ),
                ),
                (
                    "sbom",
                    models.ForeignKey(
                        blank=True,
                        help_text="SBOM artifact included in this release",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sboms.sbom",
                    ),
                ),
            ],
            options={
                "db_table": "core_release_artifacts",
                "unique_together": {("release", "document"), ("release", "sbom")},
            },
        ),
    ]
