# Generated by Django 5.2.3 on 2025-07-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_release_models_with_prerelease"),
        ("documents", "0002_alter_document_document_type"),
        ("sboms", "0034_add_product_links"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["product", "-created_at"], name="core_rel_prod_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["is_latest"], name="core_rel_is_latest_idx"),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["is_prerelease"], name="core_rel_is_prerel_idx"),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["product", "is_latest"], name="core_rel_prod_latest_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="releaseartifact",
            index=models.Index(
                fields=["release", "-created_at"], name="core_art_rel_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="releaseartifact",
            index=models.Index(fields=["sbom"], name="core_art_sbom_idx"),
        ),
        migrations.AddIndex(
            model_name="releaseartifact",
            index=models.Index(fields=["document"], name="core_art_document_idx"),
        ),
        migrations.AddIndex(
            model_name="releaseartifact",
            index=models.Index(
                fields=["release", "sbom"], name="core_art_rel_sbom_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="releaseartifact",
            index=models.Index(
                fields=["release", "document"], name="core_art_rel_doc_idx"
            ),
        ),
    ]
