# Generated by Django 5.2.7 on 2025-11-01 10:05

from django.db import migrations


def fix_keycloak_provider_id(apps, schema_editor):
    """Fix missing provider_id for Keycloak SocialApp."""
    SocialApp = apps.get_model("socialaccount", "SocialApp")

    # Update Keycloak social app to have the correct provider_id
    SocialApp.objects.filter(provider="openid_connect", name="Keycloak").update(provider_id="keycloak")


def reverse_fix_keycloak_provider_id(apps, schema_editor):
    """Reverse the provider_id fix."""
    SocialApp = apps.get_model("socialaccount", "SocialApp")

    # Clear provider_id for Keycloak social app
    SocialApp.objects.filter(provider="openid_connect", name="Keycloak", provider_id="keycloak").update(provider_id="")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_add_performance_indexes"),
        ("socialaccount", "0004_app_provider_id_settings"),
    ]

    operations = [
        migrations.RunPython(fix_keycloak_provider_id, reverse_fix_keycloak_provider_id),
    ]
