# Generated by Django 5.2.7 on 2025-11-01 10:35

from django.db import migrations


def remove_database_socialapp(apps, schema_editor):
    """
    Remove database-based SocialApp configuration for Keycloak.

    We are using settings-based configuration (SOCIALACCOUNT_PROVIDERS) instead,
    which is the modern django-allauth approach. Having both causes
    MultipleObjectsReturned errors.
    """
    SocialApp = apps.get_model("socialaccount", "SocialApp")

    # Delete any Keycloak SocialApp records from database
    deleted_count, _ = SocialApp.objects.filter(provider="openid_connect", name="Keycloak").delete()

    # Note: We don't log here because it's a migration


def reverse_remove_database_socialapp(apps, schema_editor):
    """
    Reverse operation - recreate the database SocialApp.

    This is here for completeness, but in practice we don't want to reverse this
    since we're moving to settings-based configuration.
    """
    # No-op: We don't want to recreate the database record
    # Users should rely on SOCIALACCOUNT_PROVIDERS in settings.py
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_add_performance_indexes"),
        ("socialaccount", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(remove_database_socialapp, reverse_remove_database_socialapp),
    ]
