# Generated by Django 5.2.7 on 2025-11-19 07:41

from django.db import migrations, models


def copy_released_at_from_created(apps, schema_editor):
    Release = apps.get_model("core", "Release")
    releases = Release.objects.all()
    for release in releases.iterator():
        release.released_at = release.created_at
        release.save(update_fields=["released_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_database_socialapp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="release",
            options={"ordering": ["-released_at", "-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="release",
            name="core_rel_prod_created_idx",
        ),
        migrations.AddField(
            model_name="release",
            name="released_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When this release became available",
            ),
        ),
        migrations.RunPython(copy_released_at_from_created, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["product", "-released_at"], name="core_rel_prod_released_idx"
            ),
        ),
    ]
