# Generated by Django 5.2.7 on 2025-11-19 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_release_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this release record was created",
            ),
        ),
    ]
