# Generated by Django 5.2.7 on 2026-01-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0014_alter_release_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="release",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("released_at"), descending=True, nulls_last=True
                    ),
                    "-created_at",
                ]
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="core_users_date_jo_4c6342_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_login"], name="core_users_last_lo_1136d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email_verified"], name="core_users_email_v_b2c576_idx"
            ),
        ),
    ]
