# Generated by Django 5.2 on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_release_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Version string (e.g., 'v1.0.0', '1.2.3'). Empty for legacy releases.",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["product", "version"],
                name="core_rel_prod_version_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                condition=~models.Q(version=""),
                fields=("product", "version"),
                name="unique_product_version_when_not_empty",
            ),
        ),
    ]
