# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_add_release_version_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="collection_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="release",
            name="collection_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="release",
            name="collection_update_reason",
            field=models.CharField(default="INITIAL_RELEASE", max_length=30),
        ),
    ]
