# Generated by Django 5.2.11 on 2026-02-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_release_collection_versioning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="collection_update_reason",
            field=models.CharField(
                choices=[
                    ("INITIAL_RELEASE", "Initial Release"),
                    ("VEX_UPDATED", "Vex Updated"),
                    ("ARTIFACT_UPDATED", "Artifact Updated"),
                    ("ARTIFACT_ADDED", "Artifact Added"),
                    ("ARTIFACT_REMOVED", "Artifact Removed"),
                ],
                default="INITIAL_RELEASE",
                max_length=30,
            ),
        ),
    ]
