# Generated by Django 5.2.7 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_release_collection_update_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user requested account deletion. Non-null means soft-deleted.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["deleted_at"], name="core_users_deleted_1de106_idx"),
        ),
    ]
