# Generated by Django 5.2.7 on 2026-02-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_user_deleted_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="core_users_deleted_f498ea_idx",
            old_name="core_users_deleted_1de106_idx",
        ),
    ]
