# Generated by Django 5.2.11 on 2026-02-27 13:24

import uuid

from django.db import migrations, models


def populate_release_uuids(apps, schema_editor):
    Release = apps.get_model("core", "Release")
    batch_size = 2000
    objs = list(Release.objects.filter(uuid__isnull=True))
    for obj in objs:
        obj.uuid = uuid.uuid4()
    for i in range(0, len(objs), batch_size):
        Release.objects.bulk_update(objs[i : i + batch_size], ["uuid"], batch_size=batch_size)


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0020_rename_core_users_deleted_1de106_idx_core_users_deleted_f498ea_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_release_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="release",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
