# Generated by Django 5.2 on 2026-03-11

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sbomify.apps.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_release_uuid"),
        ("sboms", "0051_add_sbom_qualifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentRelease",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("version", models.CharField(default="", max_length=255)),
                ("qualifiers", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("collection_version", models.PositiveIntegerField(default=1)),
                (
                    "collection_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "collection_update_reason",
                    models.CharField(
                        choices=[
                            ("INITIAL_RELEASE", "Initial Release"),
                            ("ARTIFACT_ADDED", "Artifact Added"),
                            ("ARTIFACT_UPDATED", "Artifact Updated"),
                            ("ARTIFACT_REMOVED", "Artifact Removed"),
                        ],
                        default="INITIAL_RELEASE",
                        max_length=30,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_releases",
                        to="sboms.component",
                    ),
                ),
            ],
            options={
                "db_table": "core_component_releases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComponentReleaseArtifact",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="core.componentrelease",
                    ),
                ),
                (
                    "sbom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sboms.sbom",
                    ),
                ),
            ],
            options={
                "db_table": "core_component_release_artifacts",
                "unique_together": {("component_release", "sbom")},
            },
        ),
        migrations.AddConstraint(
            model_name="componentrelease",
            constraint=models.UniqueConstraint(
                fields=("component", "version", "qualifiers"),
                name="unique_component_version_qualifiers",
            ),
        ),
    ]
