# Generated by Django 5.2.13 on 2026-05-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_unique_sbom_per_component_release"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductProject",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectComponent",
        ),
    ]
