# Generated by Django 5.2.14 on 2026-07-14 09:43

from django.db import migrations, models


def _mark_latest_release_pins_auto(apps, schema_editor):
    """Existing latest-release artifacts are sbomify-managed.

    They predate the flag, so they'd otherwise read as manual pins and
    ensure_latest_vex_pinned would refuse to re-point their VEX slots. Manual
    artifact management is rejected on latest releases, so every existing row
    there was created by sbomify's own maintenance.
    """
    ReleaseArtifact = apps.get_model("core", "ReleaseArtifact")
    ReleaseArtifact.objects.filter(release__is_latest=True).update(auto_pinned=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_delete_productproject_delete_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseartifact",
            name="auto_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Pinned automatically by sbomify (latest-release maintenance, or newest-VEX tracking on other releases). Only auto-pinned VEX pins are ever re-pointed when a newer VEX appears; a manually pinned artifact is never replaced automatically.",
            ),
        ),
        migrations.RunPython(_mark_latest_release_pins_auto, migrations.RunPython.noop),
    ]
