# Generated by Django 5.2.15 on 2026-07-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_releaseartifact_auto_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="newsletter_opt_in",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user is subscribed to the sbomify newsletter.",
            ),
        ),
    ]
