# Generated by Django 5.2.17 on 2026-09-28 08:38

import logging

from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower

logger = logging.getLogger(__name__)

CONSTRAINT = models.UniqueConstraint(
    Lower("email"),
    condition=models.Q(("email", ""), _negated=True),
    name="core_users_email_ci_unique",
)


def lowercase_emails_and_add_constraint(apps, schema_editor):
    """Store every address in lower case, then make addresses unique without case.

    Accounts whose addresses differ only in case are left exactly as they are:
    choosing which one keeps the address is a decision for a person. While any
    exist the constraint is not created, and the migration logs their ids.
    Resolve them, then run ``migrate core 0028`` and ``migrate core`` again.
    """
    User = apps.get_model("core", "User")
    duplicated = list(
        User.objects.exclude(email="")
        .annotate(address=Lower("email"))
        .values("address")
        .annotate(holders=Count("id"))
        .filter(holders__gt=1)
        .values_list("address", flat=True)
    )
    mixed_case = (
        User.objects.exclude(email="")
        .exclude(email=Lower("email"))
        .annotate(address=Lower("email"))
        .exclude(address__in=duplicated)
    )
    User.objects.filter(pk__in=mixed_case.values("pk")).update(email=Lower("email"))

    if duplicated:
        for address in duplicated:
            ids = sorted(User.objects.filter(email__iexact=address).values_list("id", flat=True))
            logger.warning("Accounts %s share one email address in different case", ids)
        logger.warning("Skipped %s: resolve the accounts above, then apply this migration again", CONSTRAINT.name)
        return
    schema_editor.add_constraint(User, CONSTRAINT)


def drop_constraint(apps, schema_editor):
    schema_editor.execute(f"DROP INDEX IF EXISTS {schema_editor.quote_name(CONSTRAINT.name)}")


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0028_user_newsletter_opt_in"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.AddConstraint(model_name="user", constraint=CONSTRAINT)],
            database_operations=[migrations.RunPython(lowercase_emails_and_add_constraint, drop_constraint)],
        ),
    ]
