# Generated by Django 5.2.11 on 2026-02-23 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0001_initial"),
        ("teams", "0030_team_tea_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
        migrations.AddIndex(
            model_name="accesstoken",
            index=models.Index(
                fields=["team", "user"], name="access_toke_team_id_56c481_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesstoken",
            index=models.Index(
                fields=["encoded_token"], name="access_toke_encoded_af10d4_idx"
            ),
        ),
    ]
