# Generated by Django 5.2.11 on 2026-02-23 10:42

from django.db import migrations


def auto_assign_single_team_tokens(apps, schema_editor):
    """Auto-assign unscoped tokens to the user's team when they belong to exactly one team.

    Tokens for users with multiple team memberships remain unscoped (team=NULL) because we
    cannot determine which team they were intended for. These will show a deprecation warning
    in the UI prompting the user to create new workspace-scoped tokens and delete the old ones.
    """
    AccessToken = apps.get_model("access_tokens", "AccessToken")
    Member = apps.get_model("teams", "Member")

    # Find all users who have unscoped tokens
    token_user_ids = AccessToken.objects.filter(team__isnull=True).values_list("user_id", flat=True).distinct()

    for user_id in token_user_ids:
        memberships = Member.objects.filter(user_id=user_id)
        if memberships.count() == 1:
            team_id = memberships.first().team_id
            AccessToken.objects.filter(user_id=user_id, team__isnull=True).update(team_id=team_id)


def reverse_auto_assign(apps, schema_editor):
    """Reverse: set all tokens back to unscoped (no-op safe since we can't distinguish)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0002_accesstoken_team_and_more"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(auto_assign_single_team_tokens, reverse_auto_assign),
    ]
