# Generated by Django 5.2.11 on 2026-02-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0003_auto_assign_single_team_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstoken",
            name="encoded_token",
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
