# Generated by Django 5.2.11 on 2026-02-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0004_alter_accesstoken_encoded_token"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accesstoken",
            name="access_toke_encoded_af10d4_idx",
        ),
    ]
