# Generated by Django 5.2.14 on 2026-05-20 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0005_remove_accesstoken_access_toke_encoded_af10d4_idx"),
        ("teams", "0035_alter_invitation_role_alter_member_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional expiry. NULL = never expires (personal access tokens). Set for OIDC-issued tokens which are short-lived (default 15 min).",
                null=True,
            ),
        ),
        # Partial index — only OIDC-issued tokens set ``expires_at``;
        # a full index would store a NULL entry for every PAT for no
        # payoff. The conditional shrinks the index ~100x.
        migrations.AddIndex(
            model_name="accesstoken",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="access_tokens_expires_at_idx",
            ),
        ),
    ]
