# Generated by Django 5.2.14 on 2026-05-20 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0006_accesstoken_expires_at_and_more"),
        ("teams", "0035_alter_invitation_role_alter_member_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accesstoken",
            name="access_tokens_expires_at_idx",
        ),
        migrations.AddIndex(
            model_name="accesstoken",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="access_tokens_expires_at_idx",
            ),
        ),
    ]
