# Generated by Django 5.2.14 on 2026-06-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0006_accesstoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstoken",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional expiry. NULL = never expires. Personal access tokens default to 90 days (user-selectable, may be NULL); OIDC-issued tokens are short-lived (default 15 min).",
                null=True,
            ),
        ),
    ]
