# Generated by Django 5.2.14 on 2026-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0007_alter_accesstoken_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="scopes",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Action scopes — a list of can() action strings, e.g. ['artifact:publish']. NULL = unscoped full-capability token (legacy default). An action scope can only narrow access: the user's workspace role and resource attributes still apply. Workspace scoping is the separate 'team' field.",
                null=True,
            ),
        ),
    ]
