# Generated by Django 5.2.14 on 2026-06-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0008_accesstoken_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="allowed_ips",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Optional IP allowlist — a list of IP or CIDR strings (IPv4/IPv6). A request whose client IP falls outside the list is rejected even with a valid token. NULL/empty = no restriction (legacy default).",
                null=True,
            ),
        ),
    ]
