# Generated by Django 5.2.14 on 2026-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0008_accesstoken_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent authenticated request made with this token. Throttled, so accurate to within a few minutes (see ACCESS_TOKEN_LAST_USED_THROTTLE_SECONDS). NULL = never used. Lets operators spot stale or leaked tokens to revoke.",
                null=True,
            ),
        ),
    ]
