# Generated by Django 5.2.14 on 2026-08-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0009_accesstoken_last_used_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenExpiryWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold_days", models.PositiveSmallIntegerField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiry_warnings",
                        to="access_tokens.accesstoken",
                    ),
                ),
            ],
            options={
                "db_table": "access_token_expiry_warnings",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("token", "threshold_days"),
                        name="token_expiry_warning_once",
                    )
                ],
            },
        ),
    ]
