# Generated by Django 5.2.17 on 2026-08-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_tokens", "0010_tokenexpirywarning"),
        (
            "teams",
            "0042_rename_teams_invit_email_d19291_idx_workspaces__email_77ed9e_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accesstoken",
            new_name="access_toke_workspa_298f40_idx",
            old_name="access_toke_team_id_56c481_idx",
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="team",
            field=models.ForeignKey(
                blank=True,
                db_column="workspace_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
    ]
