# Generated by Django 5.1.4 on 2025-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=30, null=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("max_products", models.IntegerField(null=True)),
                ("max_projects", models.IntegerField(null=True)),
                ("max_components", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "billing_plans",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["key"], name="billing_pla_key_be5cfe_idx")
                ],
            },
        ),
    ]
