# Generated by Django 5.1.4 on 2025-01-20 06:28

from django.db import migrations

BILLING_PLANS = [
    {
        "key": "community",
        "name": "Community",
        "description": "Community plan for small teams",
        "max_products": 1,
        "max_projects": 1,
        "max_components": 5,
    },
    {
        "key": "business",
        "name": "Business",
        "description": "Pro plan for medium teams",
        "max_products": 5,
        "max_projects": 10,
        "max_components": 200,
    },
    {
        "key": "enterprise",
        "name": "Enterprise",
        "description": "Enterprise plan for large teams",
        "max_products": None,
        "max_projects": None,
        "max_components": None,
    },
]


def add_billing_plans(apps, schema_editor):
    BillingPlan = apps.get_model("billing", "BillingPlan")
    for plan in BILLING_PLANS:
        if not BillingPlan.objects.filter(key=plan["key"]).exists():
            BillingPlan.objects.create(
                key=plan["key"],
                name=plan["name"],
                description=plan["description"],
                max_products=plan["max_products"],
                max_projects=plan["max_projects"],
                max_components=plan["max_components"],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_billing_plans, migrations.RunPython.noop),
    ]
