# Generated by Django 5.2.3 on 2025-07-08 09:25

from django.db import migrations


def populate_plan_user_limits(apps, schema_editor):
    """Populate user limits for existing billing plans."""
    BillingPlan = apps.get_model("billing", "BillingPlan")

    # Define user limits according to requirements
    plan_limits = {
        "community": 1,     # Owner only
        "business": 5,      # Up to 5 users
        "enterprise": None, # Unlimited
    }

    for plan in BillingPlan.objects.all():
        if plan.key in plan_limits:
            plan.max_users = plan_limits[plan.key]
            plan.save(update_fields=["max_users"])


def reverse_populate_plan_user_limits(apps, schema_editor):
    """Reverse the population of user limits."""
    BillingPlan = apps.get_model("billing", "BillingPlan")

    for plan in BillingPlan.objects.all():
        plan.max_users = None
        plan.save(update_fields=["max_users"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_add_max_users_to_billing_plan"),
    ]

    operations = [
        migrations.RunPython(populate_plan_user_limits, reverse_populate_plan_user_limits),
    ]
