# Generated by Django 5.2.7 on 2026-01-08 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_update_business_plan_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingplan",
            options={
                "ordering": ["name"],
                "verbose_name": "Billing Plan",
                "verbose_name_plural": "Billing Plans",
            },
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="discount_percent_annual",
            field=models.IntegerField(
                default=0,
                help_text="Promotional discount percentage for annual billing.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="discount_percent_monthly",
            field=models.IntegerField(
                default=0,
                help_text="Promotional discount percentage for monthly billing.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="max_components",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of components allowed. Leave blank for unlimited.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="max_products",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of products allowed. Leave blank for unlimited.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="max_projects",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of projects allowed. Leave blank for unlimited.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="max_users",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of users/members allowed in a team. Leave blank for unlimited.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="stripe_price_annual_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="stripe_price_monthly_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="billingplan",
            index=models.Index(
                fields=["stripe_product_id"], name="billing_pla_stripe__1893b0_idx"
            ),
        ),
    ]
