# Generated by Django 5.2.11 on 2026-03-04 14:29

import django.db.models.deletion
import sbomify.apps.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0011_document_uuid"),
        ("teams", "0032_populate_team_slugs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OSCALCatalog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                ("source_url", models.URLField(blank=True, default="")),
                ("catalog_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compliance_oscal_catalogs",
                "ordering": ["-created_at"],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="OSCALAssessmentResult",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("assessor", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in-progress", "In Progress"),
                            ("complete", "Complete"),
                        ],
                        default="in-progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oscal_assessment_results",
                        to="teams.team",
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_results",
                        to="compliance.oscalcatalog",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_oscal_assessment_results",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="OSCALControl",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("control_id", models.CharField(max_length=50)),
                ("group_id", models.CharField(max_length=50)),
                ("group_title", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="compliance.oscalcatalog",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_oscal_controls",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="OSCALFinding",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("satisfied", "Satisfied"),
                            ("not-satisfied", "Not Satisfied"),
                            ("not-applicable", "Not Applicable"),
                            ("unanswered", "Unanswered"),
                        ],
                        default="unanswered",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="compliance.oscalassessmentresult",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="compliance.oscalcontrol",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_oscal_findings",
            },
        ),
        migrations.CreateModel(
            name="OSCALObservation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EXAMINE", "Examine"),
                            ("INTERVIEW", "Interview"),
                            ("TEST", "Test"),
                        ],
                        max_length=20,
                    ),
                ),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="compliance.oscalfinding",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_oscal_observations",
            },
        ),
        migrations.AddIndex(
            model_name="oscalcontrol",
            index=models.Index(
                fields=["catalog", "group_id"], name="compliance__catalog_9edb4e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="oscalcontrol",
            unique_together={("catalog", "control_id")},
        ),
        migrations.AddIndex(
            model_name="oscalfinding",
            index=models.Index(
                fields=["assessment_result", "status"],
                name="compliance__assessm_5ee13b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="oscalfinding",
            unique_together={("assessment_result", "control")},
        ),
    ]
