# Generated by Django 5.2.11 on 2026-03-04 14:33

import django.db.models.deletion
import sbomify.apps.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
        ("core", "0021_release_uuid"),
        ("teams", "0032_populate_team_slugs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CRAAssessment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intended_use", models.TextField(blank=True, default="")),
                ("target_eu_markets", models.JSONField(default=list)),
                ("support_period_end", models.DateField(blank=True, null=True)),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("class_i", "Class I"),
                            ("class_ii", "Class II"),
                            ("critical", "Critical"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("is_open_source_steward", models.BooleanField(default=False)),
                (
                    "conformity_assessment_procedure",
                    models.CharField(
                        choices=[
                            ("module_a", "Module A"),
                            ("module_b_c", "Module B+C"),
                            ("module_h", "Module H"),
                            ("eucc", "EUCC"),
                        ],
                        default="module_a",
                        max_length=20,
                    ),
                ),
                ("vdp_url", models.URLField(blank=True, default="")),
                (
                    "acknowledgment_timeline_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "csirt_contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("security_contact_url", models.URLField(blank=True, default="")),
                (
                    "csirt_country",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("enisa_srp_registered", models.BooleanField(default=False)),
                ("incident_response_plan_url", models.URLField(blank=True, default="")),
                ("incident_response_notes", models.TextField(blank=True, default="")),
                (
                    "update_frequency",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "update_method",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("update_channel_url", models.URLField(blank=True, default="")),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("support_url", models.URLField(blank=True, default="")),
                (
                    "support_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "support_hours",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "data_deletion_instructions",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                ("completed_steps", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oscal_assessment_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cra_assessment",
                        to="compliance.oscalassessmentresult",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cra_assessment",
                        to="core.product",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cra_assessments",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_cra_assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRAExportPackage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storage_key", models.CharField(max_length=500)),
                ("content_hash", models.CharField(max_length=64)),
                ("manifest", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_packages",
                        to="compliance.craassessment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_cra_export_packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRAGeneratedDocument",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("vdp", "Vulnerability Disclosure Policy"),
                            ("security_txt", "security.txt"),
                            ("risk_assessment", "Risk Assessment"),
                            ("early_warning", "Early Warning"),
                            ("full_notification", "Full Notification"),
                            ("final_report", "Final Report"),
                            ("user_instructions", "User Instructions"),
                            ("decommissioning_guide", "Decommissioning Guide"),
                            ("declaration_of_conformity", "Declaration of Conformity"),
                        ],
                        max_length=40,
                    ),
                ),
                ("storage_key", models.CharField(max_length=500)),
                ("content_hash", models.CharField(max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_stale", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_documents",
                        to="compliance.craassessment",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_cra_generated_documents",
                "unique_together": {("assessment", "document_kind")},
            },
        ),
    ]
