# Generated by Django 5.2.12 on 2026-03-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_craassessment_craexportpackage_cragenerateddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="craassessment",
            name="support_contact_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
