# Generated by Django 5.2.12 on 2026-04-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_add_support_contact_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="craassessment",
            name="handles_financial_value",
            field=models.BooleanField(
                default=False,
                help_text="Product handles monetary value or virtual currency — triggers EN 18031-3 (fraud protection) when combined with RED.",
            ),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="is_radio_equipment",
            field=models.BooleanField(
                default=False,
                help_text="Product falls under the EU Radio Equipment Directive — triggers EN 18031-1 applicability.",
            ),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="processes_personal_data",
            field=models.BooleanField(
                default=False,
                help_text="Product processes personal data under GDPR — triggers EN 18031-2 (privacy) when combined with RED.",
            ),
        ),
    ]
