# Generated by Django 5.2.12 on 2026-04-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0004_add_red_en18031_applicability"),
    ]

    operations = [
        migrations.AddField(
            model_name="craassessment",
            name="bsi_waivers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
