# Generated by Django 5.2.12 on 2026-04-01 14:08

from django.db import migrations


def backfill_annex_part(apps, schema_editor):
    """Backfill is_mandatory and annex_part for existing OSCALControl rows.

    Part II controls (vulnerability handling, group_id='cra-vh') are always
    mandatory per CRA Art 13(4), FAQ 4.1.3. All other controls are Part I
    (risk-based).
    """
    OSCALControl = apps.get_model("compliance", "OSCALControl")

    # Mark Part II (vulnerability handling) controls as mandatory — scoped to CRA catalog only
    OSCALControl.objects.filter(
        catalog__name="EU CRA Annex I",
        group_id="cra-vh",
    ).update(
        is_mandatory=True,
        annex_part="part-ii",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0004_craassessment_harmonised_standard_applied_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_annex_part, migrations.RunPython.noop),
    ]
