# Generated by Django 5.2.12 on 2026-04-01 13:44

import django.db.models.deletion
import sbomify.apps.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0005_add_bsi_waivers"),
        ("core", "0025_unique_sbom_per_component_release"),
        ("teams", "0034_alter_team_security_txt_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="craassessment",
            name="harmonised_standard_applied",
            field=models.BooleanField(
                default=False,
                help_text="Whether a harmonised standard has been applied (CRA Art 32(2)); required for Class I + Module A",
            ),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="support_period_short_justification",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required when support period is less than 5 years (CRA Art 13(8))",
            ),
        ),
        migrations.AddField(
            model_name="oscalcontrol",
            name="annex_part",
            field=models.CharField(
                default="part-i",
                help_text="Which part of CRA Annex I this control belongs to (part-i or part-ii)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="oscalcontrol",
            name="is_mandatory",
            field=models.BooleanField(
                default=False,
                help_text="Part II (vulnerability handling) controls are always mandatory (CRA Art 13(4))",
            ),
        ),
        migrations.AddField(
            model_name="oscalfinding",
            name="justification",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required justification when Part I control is marked not-applicable (CRA Art 13(4))",
            ),
        ),
        migrations.CreateModel(
            name="CRAScopeScreening",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "has_data_connection",
                    models.BooleanField(
                        default=True,
                        help_text="Does the product have a direct or indirect logical or physical data connection? (FAQ 1.1, CRA Art 3(1))",
                    ),
                ),
                (
                    "is_own_use_only",
                    models.BooleanField(
                        default=False,
                        help_text="Is the product manufactured exclusively for own use, not placed on the EU market? (FAQ 1.5, CRA Art 2(1))",
                    ),
                ),
                (
                    "is_testing_version",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a testing/pre-release version with visible non-compliance indication? (FAQ 1.6, CRA Art 21(1))",
                    ),
                ),
                (
                    "is_covered_by_other_legislation",
                    models.BooleanField(
                        default=False,
                        help_text="Is the product covered by exempted EU legislation (medical devices, motor vehicles, civil aviation, marine equipment)? (FAQ 1.9, CRA Art 2(3-5))",
                    ),
                ),
                (
                    "exempted_legislation_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which exempted legislation applies (e.g., Regulation 2017/745 — Medical Devices)",
                        max_length=255,
                    ),
                ),
                (
                    "is_dual_use",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a dual-use product with both civilian and defence applications? (FAQ 1.8, CRA Art 2(2))",
                    ),
                ),
                ("screening_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cra_scope_screening",
                        to="core.product",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cra_scope_screenings",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_cra_scope_screenings",
            },
        ),
    ]
