# Generated by Django 5.2.12 on 2026-04-01 14:08

import logging

from django.db import migrations

_LOG = logging.getLogger("sbomify.compliance.audit")


def backfill_annex_part(apps, schema_editor):
    """Backfill ``is_mandatory`` and ``annex_part`` for every CRA control row.

    Covers every ``EU CRA Annex I`` catalog version (not just the latest),
    so assessments started against a pre-1.1.0 catalog row get the correct
    Part II mandatory marking retroactively (CRA Art 13(4), FAQ 4.1.3).
    Without this, a pre-deploy assessment could silently allow Part II
    vulnerability-handling controls to be marked N/A.

    Derivation order:
      1. Read ``annex-part`` from the control's props in the catalog JSON
         (authoritative source — matches what ``import_catalog_to_db``
         produces for new imports).
      2. Fall back to ``group_id == "cra-vh"`` heuristic for catalog rows
         whose stored JSON predates the ``annex-part`` prop (legacy 1.0.0
         imports).

    After the controls themselves are reclassified, any pre-existing
    ``OSCALFinding`` that marked a now-mandatory Part II control as
    ``not-applicable`` is reset to ``unanswered`` so the operator is
    forced to re-evaluate it. CRA Art 13(4) does not allow vulnerability-
    handling controls to be waived; leaving the old N/A status would
    silently carry forward a non-compliant state across the upgrade.
    """
    OSCALCatalog = apps.get_model("compliance", "OSCALCatalog")
    OSCALControl = apps.get_model("compliance", "OSCALControl")
    OSCALFinding = apps.get_model("compliance", "OSCALFinding")

    for catalog in OSCALCatalog.objects.filter(name="EU CRA Annex I"):
        # Build control_id → annex_part map from the catalog JSON's props.
        control_annex_part: dict[str, str] = {}
        catalog_json = catalog.catalog_json or {}
        for group in catalog_json.get("groups", []) or []:
            for control in group.get("controls", []) or []:
                cid = control.get("id")
                if not cid:
                    continue
                annex_part = "part-i"
                for prop in control.get("props", []) or []:
                    if prop.get("name") == "annex-part":
                        annex_part = prop.get("value", "part-i")
                        break
                control_annex_part[cid] = annex_part

        # Apply to every control row of this catalog. Use bulk_update to
        # avoid per-row UPDATE overhead on large catalogs.
        to_update = []
        part_ii_control_pks: list = []
        for ctl in OSCALControl.objects.filter(catalog=catalog):
            # JSON-first, group_id heuristic second (legacy 1.0.0 imports
            # may lack the ``annex-part`` prop in their stored JSON).
            derived = control_annex_part.get(
                ctl.control_id,
                "part-ii" if ctl.group_id == "cra-vh" else "part-i",
            )
            ctl.annex_part = derived
            ctl.is_mandatory = derived == "part-ii"
            to_update.append(ctl)
            if derived == "part-ii":
                part_ii_control_pks.append(ctl.pk)
        if to_update:
            OSCALControl.objects.bulk_update(to_update, ["annex_part", "is_mandatory"])

        # Reset stale N/A findings on now-mandatory Part II controls.
        # Capture the affected finding IDs + parent assessment-result IDs
        # into the audit log BEFORE the update so a regulator can
        # reconstruct which operator decisions were invalidated by the
        # CRA Part I/II reclassification. This is the only durable trace
        # of the state transition — the update itself is lossy.
        if part_ii_control_pks:
            stale_findings = list(
                OSCALFinding.objects.filter(
                    control_id__in=part_ii_control_pks,
                    status="not-applicable",
                ).values("pk", "assessment_result_id", "control_id", "justification")
            )
            if stale_findings:
                _LOG.warning(
                    "cra.migration_0007.reset_na_findings_on_part_ii",
                    extra={
                        "event": "cra.migration_0007.reset_na_findings_on_part_ii",
                        "catalog_id": catalog.pk,
                        "catalog_name": catalog.name,
                        "catalog_version": catalog.version,
                        "reset_count": len(stale_findings),
                        "reset_findings": stale_findings,
                    },
                )
            OSCALFinding.objects.filter(
                control_id__in=part_ii_control_pks,
                status="not-applicable",
            ).update(status="unanswered")


def reverse_backfill(apps, schema_editor):
    """Reset ``is_mandatory`` / ``annex_part`` on CRA controls.

    Lossy but predictable: any rollback past 0007 demotes Part II to
    Part I, matching the schema defaults set by 0006. Without an
    explicit reverse, ``RunPython.noop`` would leave the fields
    populated while 0006's schema reversal tries to drop them.

    Log the reset count so a rollback leaves a breadcrumb in the deploy
    log — re-running forward doesn't recover operator N/A decisions
    that were reset during the original forward backfill, so a
    regulator asking "what state was in place on day X" has at least a
    count to point at.
    """
    OSCALControl = apps.get_model("compliance", "OSCALControl")
    affected = OSCALControl.objects.filter(catalog__name="EU CRA Annex I").count()
    if affected:
        _LOG.warning(
            "cra.migration_0007.reverse_reset_controls",
            extra={
                "event": "cra.migration_0007.reverse_reset_controls",
                "affected_controls": affected,
            },
        )
    OSCALControl.objects.filter(catalog__name="EU CRA Annex I").update(
        is_mandatory=False,
        annex_part="part-i",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0006_craassessment_harmonised_standard_applied_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_annex_part, reverse_backfill),
    ]
