# Generated by Django 5.2.12 on 2026-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0007_backfill_oscal_control_annex_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crascopescreening",
            name="has_data_connection",
            field=models.BooleanField(
                default=True,
                help_text="Direct or indirect data connection capability (FAQ 1.1, CRA Art 3(1))",
            ),
        ),
        migrations.AlterField(
            model_name="crascopescreening",
            name="is_own_use_only",
            field=models.BooleanField(
                default=False,
                help_text="Manufactured exclusively for own use, not on EU market (FAQ 1.5, CRA Art 2(1))",
            ),
        ),
        migrations.AlterField(
            model_name="crascopescreening",
            name="is_testing_version",
            field=models.BooleanField(
                default=False,
                help_text="Testing/pre-release version with non-compliance indication (FAQ 1.6, CRA Art 21(1))",
            ),
        ),
    ]
