# Generated by Django 5.2.12 on 2026-04-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0012_tighten_annex_part_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="craassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                    ("stale", "Stale (scope changed)"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
