# Generated by Django 5.2.12 on 2026-04-30 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0013_alter_craassessment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="craassessment",
            name="signature_function",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="signature_image",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="signature_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="signature_place",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="signed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who saved the signature on this assessment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
