# Generated by Django 5.2.14 on 2026-08-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0014_add_signature_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="craassessment",
            name="authorized_rep_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="authorized_rep_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="authorized_rep_mandate_date",
            field=models.DateField(
                blank=True,
                help_text="Date the written mandate was signed (checklist 7.4.2).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="authorized_rep_mandate_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reference to the mandate document — contract id, DMS link or file name.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="authorized_rep_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="craassessment",
            name="is_eu_established",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the manufacturer has an EU establishment (checklist 7.4.1). False makes an Authorized Representative mandatory; NULL means the determination has not been made.",
                null=True,
            ),
        ),
    ]
