# Generated by Django 5.2.14 on 2026-08-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0014_add_signature_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="craexportpackage",
            name="retain_until",
            field=models.DateField(
                blank=True,
                help_text="CRA Art. 13(15) retention floor: the later of ten years after creation and the assessment's support period end. Cleanup jobs must not delete the row or its stored bundle before this date. NULL only on rows created before the field existed, which are treated as retained forever.",
                null=True,
            ),
        ),
    ]
