# Generated by Django 5.2.14 on 2026-08-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0015_craassessment_authorized_rep_address_and_more"),
        ("compliance", "0015_craexportpackage_retain_until"),
    ]

    operations = []
