# Generated by Django 5.2.14 on 2026-08-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0016_merge_20260805_0551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="craassessment",
            name="authorized_rep_mandate_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reference to the mandate document: contract id, DMS link or file name.",
                max_length=255,
            ),
        ),
    ]
