# Generated by Django 5.2.17 on 2026-08-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0017_alter_craassessment_authorized_rep_mandate_reference"),
        (
            "teams",
            "0042_rename_teams_invit_email_d19291_idx_workspaces__email_77ed9e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="craassessment",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cra_assessments",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="crascopescreening",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cra_scope_screenings",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="oscalassessmentresult",
            name="team",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oscal_assessment_results",
                to="teams.team",
            ),
        ),
    ]
