# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):
    """Respell two ``help_text`` strings in American English.

    ``help_text`` carries no SQL, so this migration is a no-op against the
    database. It exists so the already-applied 0006 can stay frozen while the
    model state still matches the models themselves.
    """

    dependencies = [
        ("compliance", "0018_alter_craassessment_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="craassessment",
            name="harmonised_standard_applied",
            field=models.BooleanField(
                default=False,
                help_text="Whether a harmonized standard has been applied (CRA Art 32(2)); required for Class I + Module A",
            ),
        ),
        migrations.AlterField(
            model_name="crascopescreening",
            name="is_dual_use",
            field=models.BooleanField(
                default=False,
                help_text="Is this a dual-use product with both civilian and defense applications? (FAQ 1.8, CRA Art 2(2))",
            ),
        ),
    ]
