# Generated by Django 5.2.14 on 2026-07-27 12:22

import django.db.models.deletion
import sbomify.apps.core.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0028_user_newsletter_opt_in"),
        ("sboms", "0066_sbom_has_crypto_assets"),
        ("teams", "0037_invitation_invitation_role_not_bot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryVulnerability",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cve_id", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("cwe_ids", models.JSONField(blank=True, default=list)),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("cvss_scores", models.JSONField(blank=True, default=list)),
                (
                    "exploitation_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("none", "No known exploitation"),
                            ("poc", "Proof of concept"),
                            ("suspected", "Suspected exploitation"),
                            ("known_exploited", "Known exploited"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("discovery_date", models.DateTimeField(blank=True, null=True)),
                ("disclosure_date", models.DateTimeField(blank=True, null=True)),
                ("recommendation", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "advisory vulnerabilities",
                "db_table": "security_advisories_vulnerabilities",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryProduct",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_advisories",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "db_table": "security_advisories_products",
                "ordering": ["product_name"],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryProductStatus",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("exploitable", "Affected"),
                            ("not_affected", "Not affected"),
                            ("false_positive", "False positive"),
                            ("in_triage", "Under investigation"),
                            ("resolved", "Fixed"),
                        ],
                        default="in_triage",
                        max_length=20,
                    ),
                ),
                (
                    "justification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("code_not_present", "Code not present"),
                            ("code_not_reachable", "Code not reachable"),
                            ("requires_configuration", "Requires configuration"),
                            ("requires_dependency", "Requires dependency"),
                            ("requires_environment", "Requires environment"),
                            ("protected_by_compiler", "Protected by compiler"),
                            ("protected_at_runtime", "Protected at runtime"),
                            ("protected_at_perimeter", "Protected at perimeter"),
                            (
                                "protected_by_mitigating_control",
                                "Protected by mitigating control",
                            ),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("can_not_fix", "Cannot fix"),
                            ("will_not_fix", "Will not fix"),
                            ("update", "Update"),
                            ("rollback", "Rollback"),
                            ("workaround_available", "Workaround available"),
                        ],
                        default="",
                        max_length=25,
                    ),
                ),
                ("impact_statement", models.TextField(blank=True, default="")),
                ("action_statement", models.TextField(blank=True, default="")),
                (
                    "recommended_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("vex_import", "VEX import")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisory_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="security_advisories.advisoryproduct",
                    ),
                ),
                (
                    "recommended_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.release",
                    ),
                ),
                (
                    "source_vex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sboms.sbom",
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_statuses",
                        to="security_advisories.advisoryvulnerability",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "advisory product statuses",
                "db_table": "security_advisories_product_statuses",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAdvisory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "advisory_type",
                    models.CharField(
                        choices=[
                            ("product_advisory", "Product advisory"),
                            ("workspace_notice", "Workspace notice"),
                        ],
                        default="product_advisory",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("gated", "Gated"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("made_public_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tracking_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("acknowledgments", models.JSONField(blank=True, default=list)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_advisories",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "security advisories",
                "db_table": "security_advisories_advisories",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="advisoryvulnerability",
            name="advisory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vulnerabilities",
                to="security_advisories.securityadvisory",
            ),
        ),
        migrations.CreateModel(
            name="AdvisoryReference",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("cve", "CVE"),
                            ("ghsa", "GitHub Security Advisory"),
                            ("euvd", "EU Vulnerability Database"),
                            ("osv", "OSV"),
                            ("mal", "OpenSSF malicious package"),
                            ("pysec", "PySec"),
                            ("rustsec", "RustSec"),
                            ("go", "Go vulnerability database"),
                            ("dsa", "Debian security advisory"),
                            ("dla", "Debian LTS advisory"),
                            ("usn", "Ubuntu security notice"),
                            ("rhsa", "Red Hat security advisory"),
                            ("alsa", "AlmaLinux security advisory"),
                            ("alas", "Amazon Linux security advisory"),
                            ("suse", "SUSE security update"),
                            ("cert_vu", "CERT/CC vulnerability note"),
                            ("zdi", "Zero Day Initiative"),
                            ("edb", "Exploit-DB"),
                            ("msrc", "Microsoft Security Response Center"),
                            ("jvndb", "JVN iPedia"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("url", models.URLField(blank=True, default="", max_length=2048)),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[("external", "External"), ("self", "Self")],
                        default="external",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vulnerability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="security_advisories.advisoryvulnerability",
                    ),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="security_advisories.securityadvisory",
                    ),
                ),
            ],
            options={
                "db_table": "security_advisories_references",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="advisoryproduct",
            name="advisory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="security_advisories.securityadvisory",
            ),
        ),
        migrations.CreateModel(
            name="AdvisoryEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("update", "Update"),
                            ("field_change", "Field change"),
                            ("status_change", "Status change"),
                            ("visibility_changed", "Visibility changed"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                            ("vulnerability_added", "Vulnerability added"),
                            ("vulnerability_removed", "Vulnerability removed"),
                            ("product_added", "Product added"),
                            ("product_removed", "Product removed"),
                            ("cra_early_warning", "CRA early warning submitted"),
                            ("cra_notification", "CRA notification submitted"),
                            ("cra_final_report", "CRA final report submitted"),
                            ("users_notified", "Impacted users notified"),
                        ],
                        max_length=30,
                    ),
                ),
                ("body", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="security_advisories.securityadvisory",
                    ),
                ),
            ],
            options={
                "db_table": "security_advisories_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryVersionRange",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "versioning_scheme",
                    models.CharField(default="generic", max_length=20),
                ),
                (
                    "introduced",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("fixed", models.CharField(blank=True, default="", max_length=100)),
                (
                    "last_affected",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fixed_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.release",
                    ),
                ),
                (
                    "introduced_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.release",
                    ),
                ),
                (
                    "last_affected_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.release",
                    ),
                ),
                (
                    "product_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_ranges",
                        to="security_advisories.advisoryproductstatus",
                    ),
                ),
            ],
            options={
                "db_table": "security_advisories_version_ranges",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["product_status"], name="sec_adv_range_status_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("fixed", ""), _negated=True),
                            models.Q(("last_affected", ""), _negated=True),
                            _negated=True,
                        ),
                        name="security_advisory_range_fixed_xor_last_affected",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("introduced", ""),
                            ("fixed", ""),
                            ("last_affected", ""),
                            _negated=True,
                        ),
                        name="security_advisory_range_needs_endpoint",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="advisoryproductstatus",
            index=models.Index(
                fields=["vulnerability"], name="sec_adv_status_vuln_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="advisoryproductstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("advisory_product__isnull", False)),
                fields=("vulnerability", "advisory_product"),
                name="security_advisory_unique_status_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="advisoryproductstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("advisory_product__isnull", True)),
                fields=("vulnerability",),
                name="security_advisory_unique_portfolio_status",
            ),
        ),
        migrations.AddIndex(
            model_name="securityadvisory",
            index=models.Index(
                fields=["team", "status"], name="sec_adv_team_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityadvisory",
            index=models.Index(
                fields=["team", "advisory_type"], name="sec_adv_team_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityadvisory",
            index=models.Index(
                fields=["team", "-updated_at"], name="sec_adv_team_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityadvisory",
            index=models.Index(
                fields=["team", "status", "visibility"],
                name="sec_adv_team_status_vis_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityadvisory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tracking_id", ""), _negated=True),
                fields=("team", "tracking_id"),
                name="security_advisory_unique_tracking_id_per_team",
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryvulnerability",
            index=models.Index(fields=["cve_id"], name="sec_adv_vuln_cve_idx"),
        ),
        migrations.AddIndex(
            model_name="advisoryvulnerability",
            index=models.Index(fields=["advisory"], name="sec_adv_vuln_advisory_idx"),
        ),
        migrations.AddConstraint(
            model_name="advisoryvulnerability",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cve_id", ""), _negated=True),
                fields=("advisory", "cve_id"),
                name="security_advisory_unique_cve_per_advisory",
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryreference",
            index=models.Index(fields=["advisory"], name="sec_adv_ref_advisory_idx"),
        ),
        migrations.AddIndex(
            model_name="advisoryreference",
            index=models.Index(fields=["vulnerability"], name="sec_adv_ref_vuln_idx"),
        ),
        migrations.AddIndex(
            model_name="advisoryreference",
            index=models.Index(
                fields=["reference_type", "external_id"],
                name="sec_adv_ref_type_extid_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="advisoryreference",
            constraint=models.CheckConstraint(
                condition=models.Q(("external_id", ""), ("url", ""), _negated=True),
                name="security_advisory_reference_needs_id_or_url",
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryproduct",
            index=models.Index(fields=["advisory"], name="sec_adv_prod_advisory_idx"),
        ),
        migrations.AddConstraint(
            model_name="advisoryproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("advisory", "product"),
                name="security_advisory_unique_product_per_advisory",
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryevent",
            index=models.Index(
                fields=["advisory", "created_at"], name="sec_adv_event_advisory_idx"
            ),
        ),
    ]
