# Generated by Django 5.2.14 on 2026-07-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_advisories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityadvisory",
            name="remediation_status",
            field=models.CharField(
                choices=[
                    ("identified", "Identified"),
                    ("investigating", "Investigating"),
                    ("fix_in_progress", "Fix in progress"),
                    ("resolved", "Resolved"),
                    ("wont_fix", "Won't fix"),
                ],
                default="identified",
                help_text="Where the team is on fixing this, kept in step with the latest status_change event",
                max_length=20,
            ),
        ),
    ]
