# Generated by Django 5.2.17 on 2026-08-25 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_user_newsletter_opt_in"),
        ("security_advisories", "0002_securityadvisory_remediation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryproductstatus",
            name="recommended_release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisory_statuses_recommending",
                to="core.release",
            ),
        ),
        migrations.AlterField(
            model_name="advisoryversionrange",
            name="fixed_release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisory_ranges_fixed_here",
                to="core.release",
            ),
        ),
        migrations.AlterField(
            model_name="advisoryversionrange",
            name="introduced_release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisory_ranges_introduced_here",
                to="core.release",
            ),
        ),
        migrations.AlterField(
            model_name="advisoryversionrange",
            name="last_affected_release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisory_ranges_last_affected_here",
                to="core.release",
            ),
        ),
    ]
