# Generated by Django 5.2.17 on 2026-08-25 17:53

import django.db.models.deletion
import sbomify.apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_user_newsletter_opt_in"),
        ("sboms", "0067_component_sbom_freshness_days"),
        (
            "security_advisories",
            "0003_alter_advisoryproductstatus_recommended_release_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryComponent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "security_advisories_components",
                "ordering": ["component_name"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="advisoryproductstatus",
            name="security_advisory_unique_portfolio_status",
        ),
        migrations.AddField(
            model_name="advisorycomponent",
            name="advisory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="security_advisories.securityadvisory",
            ),
        ),
        migrations.AddField(
            model_name="advisorycomponent",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_advisories",
                to="core.component",
            ),
        ),
        migrations.AddField(
            model_name="advisoryproductstatus",
            name="advisory_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="security_advisories.advisorycomponent",
            ),
        ),
        migrations.AddConstraint(
            model_name="advisoryproductstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("advisory_component__isnull", False)),
                fields=("vulnerability", "advisory_component"),
                name="security_advisory_unique_status_per_component",
            ),
        ),
        migrations.AddConstraint(
            model_name="advisoryproductstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("advisory_product__isnull", True),
                    ("advisory_component__isnull", True),
                ),
                fields=("vulnerability",),
                name="security_advisory_unique_portfolio_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="advisoryproductstatus",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("advisory_product__isnull", False),
                    ("advisory_component__isnull", False),
                    _negated=True,
                ),
                name="security_advisory_status_one_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="advisorycomponent",
            index=models.Index(fields=["advisory"], name="sec_adv_comp_advisory_idx"),
        ),
        migrations.AddConstraint(
            model_name="advisorycomponent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("component__isnull", False)),
                fields=("advisory", "component"),
                name="security_advisory_unique_component_per_advisory",
            ),
        ),
    ]
