# Generated by Django 5.2.17 on 2026-09-11 14:28

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_advisories", "0005_alter_securityadvisory_team"),
        ("teams", "0044_team_csaf_feed_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="securityadvisory",
            index=models.Index(
                models.F("team"),
                django.db.models.functions.text.Concat(
                    models.Func(
                        django.db.models.functions.text.Lower(
                            django.db.models.functions.comparison.Coalesce(
                                django.db.models.functions.comparison.NullIf(
                                    models.F("tracking_id"), models.Value("")
                                ),
                                models.F("id"),
                            )
                        ),
                        models.Value("[^+a-z0-9-]"),
                        models.Value("_"),
                        models.Value("g"),
                        function="REGEXP_REPLACE",
                        output_field=models.CharField(),
                    ),
                    models.Value(".json"),
                    output_field=models.CharField(),
                ),
                name="sec_adv_csaf_filename_idx",
            ),
        ),
    ]
